### ISSUE TITLE
The license is not open source

### ISSUE THREAD

**Issue by danieljl** [facebookresearch/LASER#11]
Hi,

The title of [the blog post](https://code.fb.com/ai-research/laser-multilingual-sentence-embeddings/) suggests that LASER is an open-source library, but the license file doesn't say so. It is not [an OSI-approved license](https://opensource.org/licenses/alphabetical) and even does not permit commercial use.

Is there any plan to change the license to an OSI-approved license (MIT, BSD, Apache)?

**Comment by hoschwenk** [comment]
Hello,
it is likely that we will switch to another license in the future.

**Comment by PiotrCzapla** [comment]
Hi, Thank you for the fantastic work!

Do you have any guidelines when will such switch happen? I've noticed on Fiass that it's license has evolved in the same way from noncommercial to bsd over a period of a few months. Do you have some guidelines you can share?

**Comment by hoschwenk** [comment]
Yes, we usually start with the current license and then evolve over time if there is demand and success for the project (which seems to be the case for LASER ;-)
However, I can't tell you how long this will take - a couple of weeks ?

**Comment by hoschwenk** [comment]
The license was changed to BSD.
