### ISSUE TITLE
ValueError: attempt to get argmax of an empty sequence

### ISSUE THREAD

**Issue by Panshangka** [facebookresearch/LASER#111]
I try to process zh-en data (https://comparable.limsi.fr/bucc2018/bucc2018-zh-en.training-gold.tar.bz2) using bucc listed in tasks, but get this error ValueError: attempt to get argmax of an empty sequence, here is my trace back:
`Processing BUCC data in .
 - Encoder: loading /home/asd/Project/LASER/models/bilstm.93langs.2018-12-26.pt
 - Tokenizer:  in language zh  
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.701 seconds.
Prefix dict has been built succesfully.
 - fast BPE: processing tok
 - Encoder: bpe to bucc2018.zh-en.train.enc.zh
 - Encoder: 0 sentences in 0s
 - Encoder: loading /home/asd/Project/LASER/models/bilstm.93langs.2018-12-26.pt
 - Tokenizer:  in language en  
 - fast BPE: processing tok
 - Encoder: bpe to bucc2018.zh-en.train.enc.en
 - Encoder: 0 sentences in 0s
Loading faiss with AVX2 support.
LASER: tool to search, score or mine bitexts
 - knn will run on all available GPUs (recommended)
 - loading texts ./embed/bucc2018.zh-en.train.txt.zh: 0 lines, 0 unique
 - loading texts ./embed/bucc2018.zh-en.train.txt.en: 0 lines, 0 unique
 - Embeddings: ./embed/bucc2018.zh-en.train.enc.zh, 0x1024
 - unify embeddings: 0 -> 0
 - Embeddings: ./embed/bucc2018.zh-en.train.enc.en, 0x1024
 - unify embeddings: 0 -> 0
 - perform 4-nn source against target
/home/asd/Project/LASER/source/mine_bitexts.py:228: RuntimeWarning: Mean of empty slice.
  x2y_mean = x2y_sim.mean(axis=1)
 - perform 4-nn target against source
/home/asd/Project/LASER/source/mine_bitexts.py:234: RuntimeWarning: Mean of empty slice.
  y2x_mean = y2x_sim.mean(axis=1)
 - mining for parallel data
 - scoring 0 candidates
 - scoring 0 candidates
Traceback (most recent call last):
  File "/home/asd/Project/LASER/source/mine_bitexts.py", line 270, in <module>
    fwd_best = x2y_ind[np.arange(x.shape[0]), fwd_scores.argmax(axis=1)]
ValueError: attempt to get argmax of an empty sequence
 - Encoder: loading /home/asd/Project/LASER/models/bilstm.93langs.2018-12-26.pt
 - Tokenizer:  in language zh  
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.666 seconds.
Prefix dict has been built succesfully.
 - fast BPE: processing tok
 - Encoder: bpe to bucc2018.zh-en.test.enc.zh
 - Encoder: 0 sentences in 0s
 - Encoder: loading /home/asd/Project/LASER/models/bilstm.93langs.2018-12-26.pt
 - Tokenizer:  in language en  
 - fast BPE: processing tok
 - Encoder: bpe to bucc2018.zh-en.test.enc.en
 - Encoder: 0 sentences in 0s
Loading faiss with AVX2 support.
LASER: tool to search, score or mine bitexts
 - knn will run on all available GPUs (recommended)
 - loading texts ./embed/bucc2018.zh-en.test.txt.zh: 0 lines, 0 unique
 - loading texts ./embed/bucc2018.zh-en.test.txt.en: 0 lines, 0 unique
 - Embeddings: ./embed/bucc2018.zh-en.test.enc.zh, 0x1024
 - unify embeddings: 0 -> 0
 - Embeddings: ./embed/bucc2018.zh-en.test.enc.en, 0x1024
 - unify embeddings: 0 -> 0
 - perform 4-nn source against target
/home/asd/Project/LASER/source/mine_bitexts.py:228: RuntimeWarning: Mean of empty slice.
  x2y_mean = x2y_sim.mean(axis=1)
 - perform 4-nn target against source
/home/asd/Project/LASER/source/mine_bitexts.py:234: RuntimeWarning: Mean of empty slice.
  y2x_mean = y2x_sim.mean(axis=1)
 - mining for parallel data
 - scoring 0 candidates
 - scoring 0 candidates
Traceback (most recent call last):
  File "/home/asd/Project/LASER/source/mine_bitexts.py", line 270, in <module>
    fwd_best = x2y_ind[np.arange(x.shape[0]), fwd_scores.argmax(axis=1)]
ValueError: attempt to get argmax of an empty sequence
usage: bucc.py [-h] [--encoding ENCODING] --src-lang SRC_LANG --trg-lang
               TRG_LANG --bucc-texts BUCC_TEXTS --bucc-ids BUCC_IDS
               --candidates CANDIDATES [--gold GOLD] [--threshold THRESHOLD]
               [--output OUTPUT] [--verbose]
bucc.py: error: argument --threshold: expected one argument`

I just started to use this repo, here is what I did:
step1: installing the dependencies: https://github.com/facebookresearch/LASER#dependencies
step2: export LASER="${HOME}/projects/laser"
step3:bash ./install_models.sh
step4: bash ./install_external_tools.sh (I didn't install mecab)
step5: download the data https://comparable.limsi.fr/bucc2018/bucc2018-zh-en.training-gold.tar.bz2
step6: run bash bucc.sh

Then I got the above error. Thanks

**Comment by hoschwenk** [comment]
Something seems to be wrong in the preprocessing pipeline since no sentences were encoded:
"Encoder: 0 sentences in 0s"
i.e. the error happens well before performing bitext mining.
Please check if some of the required pre-processing tools are missing, e.g. failed installation for whatever reason (mecab is not needed for your languages), or they are not found during encoding.
You should also check whether the download of the BUCC corpus is correct.

**Comment by Panshangka** [comment]
> Something seems to be wrong in the preprocessing pipeline since no sentences were encoded:
> "Encoder: 0 sentences in 0s"
> i.e. the error happens well before performing bitext mining.
> Please check if some of the required pre-processing tools are missing, e.g. failed installation for whatever reason (mecab is not needed for your languages), or they are not found during encoding.
> You should also check whether the download of the BUCC corpus is correct.

I'm sure that the BUCC corpus is correct, and I find that all the files in bucc2018/embed directory is all empty 0:
`0       bucc2018.zh-en.test.txt.en
0       bucc2018.zh-en.test.txt.zh
0       bucc2018.zh-en.train.candidates.tsv
0       bucc2018.zh-en.train.enc.en
0       bucc2018.zh-en.train.enc.zh
0       bucc2018.zh-en.train.id.en
0       bucc2018.zh-en.train.id.zh
0       bucc2018.zh-en.train.txt.en
0       bucc2018.zh-en.train.txt.zh`

Still working on it trying to figure out why
