### ISSUE TITLE
Codes for bitext mining

### ISSUE THREAD

**Issue by LukeTu** [facebookresearch/LASER#112]
Hi and thank you for releasing the bitext mining code!

The approach looks very inspiring! However, it seems that the code you are providing is only applicable to the data from BUCC. Would it be possible for you to make it work for some general monolingual plain texts? That could be very helpful, thanks!

My research focuses on the parallel sentences from the revision of multi-lingual Wiki-texts. I know the Wikimatrix is out there, maybe it will also be very helpful if the code for mining Wiki-texts is available there!

Sorry, I'm just a beginner on digital humanity. I will be very grateful if you could help me out.

**Comment by mohammedayub44** [comment]
@LukeTu  did you happen to use this for any custom datasets.. like mining from wikipedia articles ?
