### ISSUE TITLE
how to tokenize a mix of languages

### ISSUE THREAD

**Issue by weiczhu** [facebookresearch/LASER#114]
hi, 
we know that Laser has used different tokenizers for languages like English, Chinese, Japanese.
if one sentence has multiple languages
e.g. 
a mix of English and Chinese in one sentence ["我喜欢Nike"]
or multilingual batch ["I like Nike", "我喜欢耐克"]

how to use a mix of tokenizer in these cases?

**Comment by hoschwenk** [comment]
If you have sentences with words different languages, tokenization is indeed tricky, in particular when the tokenization techniques of the involved languages are very different, e.g. en and zh in your case.
In your case, I would recommend to run ZH tokenization.

For a batch of sentences in multiple languages, you should process them separately.

The next version of LASER will use an unified tokenizer, e.g. sentence piece, and you won't have this problem any longer.
