### ISSUE TITLE
Using embed.sh gives the following warning (Setting locale failed)

### ISSUE THREAD

**Issue by prabhakar267** [facebookresearch/LASER#119]
When I run `embed.sh` with any language code other than "en", the following warning comes up, I am able to get the embeddings but I doubt whether the correct tokenization happened? Is there any fix for this?
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
```

**Comment by hoschwenk** [comment]
This looks like an installation issue on you machine.
You may want to try to install the missing language pack.
I'm sorry, but it can't help you further.
