### ISSUE TITLE
MLDoc dataset unavailable

### ISSUE THREAD

**Issue by mihirkale815** [facebookresearch/LASER#12]
TREC website has been down for several days. So we cannot access the MLdoc dataset, which was used in the paper for zero shot text classification. Any other way to download the data?

**Comment by hoschwenk** [comment]
Hello,
MLDoc is extracted form the Reuters RCV2 corpus.
RCV2 has a copyright and we can't distribute it directly.
I hope that the TREC server will be soon on-line soon.
