### ISSUE TITLE
Check if a word was part of the training dataset

### ISSUE THREAD

**Issue by verma6uc** [facebookresearch/LASER#123]
Is there a way I can check if a word (in any language) was considered when the training happened?
For example, a word like "Vaibhav", will not probably be embedded correctly and is best ignored while performing embedding and comparisons.

**Comment by bricksdont** [comment]
Why do you suspect that this particular word would not be embedded correctly, and is best ignored?

LASER does not embed words per se, but _subwords_. It is likely that a word like `Vaibhav` is split into several parts, and those parts are embedded individually.

**Comment by hoschwenk** [comment]
It is not possible to look up whether a particular word was part if the training data or not (we use 220M sentences !).
In addition, as @bricksdont wrote, we use BPE encoding.
You can apply BPE on your text using the provided vocabulary and see how your words are handled
