### ISSUE TITLE
CCMatrix data

### ISSUE THREAD

**Issue by prajdabre** [facebookresearch/LASER#124]
Hello,
When will the CCMatrix data or relevant extraction scripts be released?
Thanks.

**Comment by ShunChi100** [comment]
Same Question. Really hope to use the data for my research projects.

**Comment by siulkilulki** [comment]
Hi,
I'm also waiting to use them in my research project

**Comment by Mr-wang2016** [comment]
+1

**Comment by smart-patrol** [comment]
Yeah, came here from the announcement to find only the results...

**Comment by zrlhk** [comment]
hope too.

**Comment by telnasser** [comment]
+1

**Comment by Elbria** [comment]
+1

**Comment by kshre** [comment]
+1

**Comment by pks** [comment]
+1 :-)

**Comment by ArbinTimilsina** [comment]
+1

**Comment by leocaprio** [comment]
+1 :+1:

**Comment by alrojo** [comment]
+1

**Comment by joytianya** [comment]
+1

**Comment by Josh-Payne** [comment]
+1, @hoschwenk any estimates on an update? :)

**Comment by adityanshastry** [comment]
+1

**Comment by shamilcm** [comment]
+1

**Comment by reachtarunhere** [comment]
Hi! Any update on the release?

**Comment by hoschwenk** [comment]
Hello,
we are really sorry for the long delay and silence.
Good news is that we were able to substantially improve CCMtarix: we now have 10.8 billions sentences for 80ish languages !

We are finalizing some details and hope to release scripts to reproduce the data this week.

**Comment by gvskalyan** [comment]
Hi @hoschwenk , sorry to ask this here.
Is there a LASER 2.0 Version in this repo or are you guys planning to release it as a different one?
[Source](https://ai.facebook.com/blog/introducing-many-to-many-multilingual-machine-translation)

Thanks.

**Comment by luofuli** [comment]
> Hello,
> we are really sorry for the long delay and silence.
> Good news is that we were able to substantially improve CCMtarix: we now have 10.8 billions sentences for 80ish languages !
> 
> We are finalizing some details and hope to release scripts to reproduce the data this week.

Hello, does the data release now?

**Comment by gwenzek** [comment]
http://data.statmt.org/cc-matrix/

**Comment by bittlingmayer** [comment]
See https://github.com/facebookresearch/LASER/issues/190
