### ISSUE TITLE
Generate parallel data for custom domain texts

### ISSUE THREAD

**Issue by mohammedayub44** [facebookresearch/LASER#128]
Hi,

I have a domain (health and/or finance) data set of 100k English sentences, I need synthetic parallel sentences for these in multiple languages (Spanish, Arabic, Indonesian etc.). I wondering how I can use LASER toolkit to generate this. I looked through the tasks folders but did not find an exact tutorial to do so. 

Can I just download the multilingual encoder, embed my custom data set and start finding similar sentences ? Guessing I need embed target sentences as well. Not sure where to start. 

New to this, any help is appreciated. 

Cheers !

**Comment by hoschwenk** [comment]
You could run the mining code on the embedded sentences, but 100k sentences to mine is very little, and you also need sentences in each foreign language.
If you collect arbitrary corpora, you can't expect that many are parallel, could be less than 1%!
Therefore, it is unlikely that you'll find an substantial amount of parallel sentences when mining in 100k texts only.
It may be better to get existing parallel sentence and look for those in your domain.
