### ISSUE TITLE
Where can I find the language id mapping?

### ISSUE THREAD

**Issue by xiankgx** [facebookresearch/LASER#133]
Can anyone point me as to where can I find the list of supported languages and id (English -> en)?

**Comment by bittlingmayer** [comment]
Do you mean for LASER, WikiMatrix or CCMatrix?

Generally you can combine https://github.com/facebookresearch/LASER#supported-languages with https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes, although I agree it would be nice if projects like this provided it in a machine readable format.

**Comment by hoschwenk** [comment]
Thanks @bittlingmayer for the answer !
Yes, we use the official iso2 codes when possible, i.e. except for the languages that only have a 3-letter code

**Comment by mprinc** [comment]
Hi @bittlingmayer , @hoschwenk 
For Serbian, Croatian and Macedonian, none of the codes works:

```sh
bash ./embed.sh ${LASER}/data/tatoeba/v1/tatoeba.srp-eng.srp sr my_embeddings_srp.raw
bash ./embed.sh ${LASER}/data/tatoeba/v1/tatoeba.srp-eng.sr sr my_embeddings_srp.raw
bash ./embed.sh ${LASER}/data/tatoeba/v1/tatoeba.hrv-eng.hrv hrv  my_embeddings_hrv.raw
bash ./embed.sh ${LASER}/data/tatoeba/v1/tatoeba.hrv-eng.hrv hr  my_embeddings_hrv.raw
bash ./embed.sh ${LASER}/data/tatoeba/v1/tatoeba.mkd-eng.mkd mk my_embeddings_mkd.raw
bash ./embed.sh ${LASER}/data/tatoeba/v1/tatoeba.mkd-eng.mkd mkd my_embeddings_mkd.raw
```

WARNING: No known abbreviations for language 'srp', attempting fall-back to English version...

**Comment by taoztw** [comment]
Hey, Why can't I find the corresponding language code for Chinese, English and Japanese in the list ?
