### ISSUE TITLE
Regarding LASER Model feature

### ISSUE THREAD

**Issue by divyag11** [facebookresearch/LASER#134]
LASER embeddings are really good, but for the use case:
Suppose:
I have text in ENGLISH and I have to match that provided text in English in any german language document. So, the laser multilingual embeddings will help me find that similar sentence in the German document.
BUT, my question is how do I translate that german similar sentence into English sentence using LASER?

**Comment by hoschwenk** [comment]
The goal of the LASER project is to provide language agnostic sentence embeddings.
However, machine translation is a totally different task. You can either try to use an existing MT system (online or download an existing model and run it on you machine), or train you own custom one.
You may use https://github.com/pytorch/fairseq, but there are of course more toolkits with models.

**Comment by divyag11** [comment]
Thanks a lot for your solution
