### ISSUE TITLE
Is there a truncation for long sentences? 

### ISSUE THREAD

**Issue by dataislife** [facebookresearch/LASER#137]
Hi, 
Given a sentence s = [x_1, x_2, ...., x_N] is there a maximum length above which we truncate the sentence? 
By that, I mean: let n be the maximum length. If N>n, do we map sentence s to map(s) = [x_1, x_2, ..., x_n] and hence remove all words at indices above n? 

Regards,

**Comment by hoschwenk** [comment]
There's a limit somewhere (I have to dig into the code ;-), but it is well beyond a reasonable length of a normal sentence (>>100 words). A longer sequence can be certainly split into several sentences.
In your question x_i are words ? Remember that you'll get ONE embedding for the whole sentence not the individual words. LASER is a sentence embedding approach, you'll get a 1k embedding for any sentence, independent of its length ! As I mentioned above, there's somewhere an internal buffer limit, but this should not be a problem in normal applications.

**Comment by dataislife** [comment]
Hi @hoschwenk , 

Just bringing back this topic 😄. I am well aware of LASER capabilities in terms of providing sentence embeddings and I have used them quite a lot in the past. Good job again on that! 

In this [file](https://github.com/facebookresearch/LASER/blob/5767f189fb4b87227e9a5a36e03ace108dc3cc2f/source/embed.py#L129 ), we can see that there is a  self.max_tokens parameter. I know that BERT-like models usually have a default parameter of max_tokens set to 512 tokens. I cannot see where you guys set this parameter exactly. Any help would be appreciated here! 

Thanks,

**Comment by Amit-GH** [comment]
I think this issue isn't concerned about longer sentences getting truncated but rather wants longer sentences to get truncated. I have a similar application where I am comparing different sentence embedding models. In other models, I can set max_length to, say, 512 but in LASER I don't see an option to truncate the sentence tokens if they are too long. Could you tell if it's even possible to pass a max_length type of argument to the model/tokenizer?
