### ISSUE TITLE
Turkish

### ISSUE THREAD

**Issue by yaziciemre** [facebookresearch/LASER#140]
Hello all,

Turkish has been shown in the supported languages list. But when I try to use it in Turkish it says

WARNING: No known abbreviations for language 'tr', attempting fall-back to English version...

I have used, tr, TR, tur, TUR, turkish, tr-tr, TR-tr 

None of them works.

Can you please help me?

**Comment by hoschwenk** [comment]
Hello,
LASER supports Turkish very well, i.e. the embeddings should be of high quality.
The warning you see means that we do not use a specific TOKENIZER for Turkish and that the system fall-backs to the English rules of the Moses tokenizer (which we believe is the best available choice).
Go ahead and enjoy LASER for Turkish :-)
("tr" is the correct language code)
