### ISSUE TITLE
Fail to install fastBPE

### ISSUE THREAD

**Issue by songhuiming** [facebookresearch/LASER#153]
Hi, I failed to install fastBPE with error like `cc1plus: error: unrecognized command line option "-std=c++11"`. Does anyone has similar issue and share your experience?

Thank you.

**Comment by hoschwenk** [comment]
We will release the LASER2 model by the end of the month. It will use SPM for all languages, and fastBPE, Moses/Jieba/Mecab tokenizers are not needed any more. This indirectly resolves  your problem :-)

Therefore, I propose to close this issue.
