### ISSUE TITLE
Codes for for Serbian, Croatian and Macedonian languages don't work

### ISSUE THREAD

**Issue by mprinc** [facebookresearch/LASER#157]
Hi @bittlingmayer , @hoschwenk

After confirming that English and French languages work fine, for Serbian, Croatian and Macedonian, none of the language codes works:

bash ./embed.sh ${LASER}/data/tatoeba/v1/tatoeba.srp-eng.srp sr my_embeddings_srp.raw
bash ./embed.sh ${LASER}/data/tatoeba/v1/tatoeba.srp-eng.srp srp my_embeddings_srp.raw
bash ./embed.sh ${LASER}/data/tatoeba/v1/tatoeba.hrv-eng.hrv hrv  my_embeddings_hrv.raw
bash ./embed.sh ${LASER}/data/tatoeba/v1/tatoeba.hrv-eng.hrv hr  my_embeddings_hrv.raw
bash ./embed.sh ${LASER}/data/tatoeba/v1/tatoeba.mkd-eng.mkd mk my_embeddings_mkd.raw
bash ./embed.sh ${LASER}/data/tatoeba/v1/tatoeba.mkd-eng.mkd mkd my_embeddings_mkd.raw
WARNING: No known abbreviations for language 'sr', attempting fall-back to English version...

Similar to https://github.com/facebookresearch/LASER/issues/133, but there was no precise answer where we can find all language codes neither?

**Comment by hoschwenk** [comment]
When running LASER, please use the 2-letter ISO language codes, e.g. "hr" and not "hrv".
However, the original Tatoeba corpus use always 3-letter ISO codes and we kept them in the test set.

The warning "No known abbreviations for language 'sr', attempting fall-back to English version" does not come from the LASER code itself, but the Moses tokenizer. This tokenizer has specific rules for 20-ish languages, all other fall-back to English (or a similar language, e.g. ast -> es)
You can ignore these warnings.
