### ISSUE TITLE
CC_ Matrix，v1.0.alpha had some data that might not meet the requirements

### ISSUE THREAD

**Issue by wanghao87x** [facebookresearch/LASER#163]
CC_ Matrix
Three days ago, some data in v1.0.alpha may not meet the requirements, and the data is the same as the previous v1.0 release. But when I want to run it, all the data is skipped, at least 2018-34-0000 tsv.gz And 2018-34-0001 tsv.gz incorrect. I found that they didn't have a score for each row, so they would jump out when they ran to assert error.
Is it the wrong way I use it?
![image](https://user-images.githubusercontent.com/43267112/99375569-d8db7f80-28fe-11eb-8a58-de418f08c631.png)

![image](https://user-images.githubusercontent.com/43267112/99376633-26a4b780-2900-11eb-8ac7-9e358805989d.png)

**Comment by gwenzek** [comment]
> and the data is the same as the previous v1.0 release

There was a few files available as "v1.0"at some point but I uploaded them by mistake and I'm not exactly sure what was distributed there, you should probably not base on this.

"v1.0.alpha" is missing the scores, so you need to use the version of the code that was released with it, or at least the definition of classes: https://github.com/facebookresearch/LASER/blob/6f9ce1ce08/tasks/CCMatrix/dl_cc_matrix.py#L12-L24

Or just use v.1.0.beta. :-)

Also v1.0 should arrive in under two weeks.

**Comment by wanghao87x** [comment]
Okay, there is another question I want to know, the beta version has a lot of data packages, does it take a long time to run this program?
I used the server cpu occupancy rate of 600%+ on vultr configured as follows to run for a whole day, and the result was still less than 5%.
CPU:
8 vCore
RAM:
32768 MB
Storage:
640 GB SSD
Bandwidth:
2838.9 GB of 6000 GB

**Comment by oneraghavan** [comment]
@gwenzek  What is the size of alpha dataset ?

**Comment by hoschwenk** [comment]
Please try the latest version of the script.
You should be able to get all the data with exception of some low-resource languages.
