### ISSUE TITLE
joint multilingual space min/max dimensions

### ISSUE THREAD

**Issue by curryprogrammer** [facebookresearch/LASER#166]
Hello,

i'm new to LASER and machine learning in general. So LASER transforms sentence into 1024-dimensional vector. What are the max/min values for each item (or feature?) in the vector? Are those floats between -0.5 and 0.5?

**Comment by avidale** [comment]
The values of the features are predicted with a linear layer without any nonlinearity with limited range (such as sigmoid) or normalization, so they are theoretically unbounded. 

For some applications, though, it makes sense to apply L2 normalization to the embeddings, which would set their bounds from -1 to 1.
