### ISSUE TITLE
Can you please upload English Nepali model as well?

### ISSUE THREAD

**Issue by mani-rai** [facebookresearch/LASER#168]
I found eng-nep model is already trained via [wmt19 task](https://www.aclweb.org/anthology/W19-5435.pdf) paper. It would be great help for me if it is provided as well. Is there's any possibility to upload this model as well?

**Comment by heffernankevin** [comment]
Hi @mani-rai, a LASER3 model for Nepali has recently been made available! The full list of available encoders is [here](https://github.com/facebookresearch/LASER/tree/main/nllb#list-of-available-laser3-encoders), which includes Nepali. You could download this encoder using the following command: `./LASER/nllb/download_models.sh npi_Deva`.

**Comment by heffernankevin** [comment]
(Closing as model for Nepali released)
