### ISSUE TITLE
failed to download tokenizer/detokenizer.perl & normalize-punctuation.perl

### ISSUE THREAD

**Issue by dcmouth** [facebookresearch/LASER#171]
when I run  similarity.py.it raise error normalize-punctuation.perl: not found. I have already run install_external_tools to download it. I found that the URL “https://raw.githubusercontent.com/moses-smt/mosesdecoder/RELEASE-4.0/scripts” where we download normalize-punctuation.perl is unreachable.when we visit it,it raise 404 . how can I do to solve this problem.
Thanks

**Comment by heffernankevin** [comment]
Closing as user mentioned this issue was resolved in https://github.com/facebookresearch/LASER/issues/212#issuecomment-1193476594.
