### ISSUE TITLE
CCMatrix : The downloaded data from the script doesn't match the expected data sizes

### ISSUE THREAD

**Issue by EL-SHREIF** [facebookresearch/LASER#176]
**I have downloaded the "v1.0.beta" version of the data and get all the language pairs and I got these numbers:**

![image](https://user-images.githubusercontent.com/36492402/107503091-33a11200-6ba2-11eb-8589-27b35e7f696d.png)

I don't know why the numbers aren't the same? Is this means that the "v1.0" will include the missing data?

Also when will "v1.0" be available?

Also regardless the missing languages like English, Japanese and Chinese The other language sentences don't fully aligned for example in "ar-fr" we have:
-  3,195,877 Sentences in fr
-  3,134,825 Sentences in ar
- Only 680,546 Sentences are aligned Which is 20% only of the data size
Why not the full data aligned? Is this will be solved in "v1.0"?

@gwenzek

**Comment by gwenzek** [comment]
What do you mean by `Only 680,546 Sentences are aligned` ?
This doesn't seems normal. How do you align them ? Normally the `ar` and `fr` files need to be joined  on their `id`.
How do you join them ?
Can you post the beginning of the files that you have ?

**Comment by EL-SHREIF** [comment]
@gwenzek 
> What do you mean by `Only 680,546 Sentences are aligned` ?

**I mean that the sentences that has the same IDs are only 680,546 sentence.**

> This doesn't seems normal. How do you align them ? Normally the `ar` and `fr` files need to be joined on their `id`.
> How do you join them ?

**I just select the sentences that has the same ID**

> Can you post the beginning of the files that you have ?

**Sure**
![image](https://user-images.githubusercontent.com/36492402/107625645-47fa1300-6c65-11eb-809f-e87e2707e411.png)

The case that I state which is the number of sentences that has the same id are less than the total number of sentences in the language pair. This case exist in all the language pairs available.

Will the rest of the data will be available in "v1.0"? When will "v1.0" released?
Is the expected number here in this image will be available in "v1.0"?
![image](https://user-images.githubusercontent.com/36492402/107623741-7e825e80-6c62-11eb-93de-c260f39fdff2.png)

**Comment by EL-SHREIF** [comment]
@gwenzek  Any updates?

**Comment by gwenzek** [comment]
I think there might be an issue with your download, you should not be missing that many sentences. Normally the id range should be continuous. Can you try again ?

**Comment by gwenzek** [comment]
also see https://github.com/facebookresearch/LASER/issues/156#issuecomment-781528208

**Comment by hoschwenk** [comment]
v1.0 is available. Please try the latest version of the script.
