### ISSUE TITLE
Slow download of CCMatrix/CCnet

### ISSUE THREAD

**Issue by critias** [facebookresearch/LASER#179]
Hi,
thanks for releasing the script to download CCMatrix. I have a few questions regarding the dl_cc_matrix.py  script:
I started the download of CCNet a couple of weeks ago by calling ‘dl_cc_matrix.py dl’. By now it downloaded about 29GB. I’m sure the internet connection is a lot faster than that. Is that download speed normal or did I do something wrong? How much data will roughly be downloaded in total? (to estimate how much longer it will take)

Finally, what happens when I kill and restart the script? Should it continue where it was or start again from the beginning?

I used the script version from commit 9b33d3a1021ed37e02cb5fd590eec70cb54f1a77 since it was the latest version when I started.

**Comment by thpun** [comment]
Also wanna know how much data would be downloaded (i mean byte transferred).

I personally used `iftop` to monitor my network performance. My bandwidth is 1Gbps and the download speed is usually around 500Mbps, given that I'm running 160 workers.
And I modified the download script to only download subset of language pairs.
So far i have downloaded over 64TB (closed the monitor once so the number in `iftop` is not accurate) and saved 35GB in disk.
![image](https://user-images.githubusercontent.com/31913095/111605646-6ed1d900-8811-11eb-9711-b2e4d48be82d.png)

**Comment by gwenzek** [comment]
> And I modified the download script to only download subset of language pairs.

This will only decrease the disk usage, but not so much the network usage.

I recommend using http://data.statmt.org/cc-matrix/ directly instead of re-running the pipeline yourself which is very long
