### ISSUE TITLE
Looking for clear instructions on building the mecab package ...

### ISSUE THREAD

**Issue by ohmeow** [facebookresearch/LASER#18]
The "pip install" failed but the external tools installer said it was better to build from source.  Unfortunately, I haven't been able to find clear documentation for how to do this.

Any help would be appreciated.

**Comment by noowad** [comment]
To use Mecab in Python, you first need to install Mecab to your environment.
you can refer to https://github.com/jordwest/mecab-docs-en.

**Comment by sfarina** [comment]
your mileage may vary:
    conda create --name laser python=3.6
    # install all the laser stuff
    git clone https://github.com/taku910/mecab.git
    cd mecab/mecab
    ./configure --prefix=/usr/local
    make
    sudo make install
    cd python
    python setup.py install

**Comment by vyraun** [comment]
@sfarina The last command gives:

running build
running build_py
running build_ext
building '_MeCab' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/py36/include -arch x86_64 -I/anaconda3/envs/py36/include -arch x86_64 -I/usr/local/include -I/anaconda3/envs/py36/include/python3.6m -c MeCab_wrap.cxx -o build/temp.macosx-10.7-x86_64-3.6/MeCab_wrap.o
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
MeCab_wrap.cxx:2375:23: warning: explicitly assigning value of variable of type 'int' to itself [-Wself-assign]
                  res = SWIG_AddCast(res);
                  ~~~ ^              ~~~
MeCab_wrap.cxx:2378:23: warning: explicitly assigning value of variable of type 'int' to itself [-Wself-assign]
                  res = SWIG_AddCast(res);                  
                  ~~~ ^              ~~~
MeCab_wrap.cxx:2900:9: warning: variable 'res' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
    if (PyType_Ready(tp) < 0)
        ^~~~~~~~~~~~~~~~~~~~
MeCab_wrap.cxx:2924:10: note: uninitialized use occurs here
  return res;
         ^~~
MeCab_wrap.cxx:2900:5: note: remove the 'if' if its condition is always false
    if (PyType_Ready(tp) < 0)
    ^~~~~~~~~~~~~~~~~~~~~~~~~
MeCab_wrap.cxx:2881:10: note: initialize the variable 'res' to silence this warning
  int res;
         ^
          = 0
MeCab_wrap.cxx:2987:10: fatal error: 'stdexcept' file not found
#include <stdexcept>
         ^~~~~~~~~~~
4 warnings and 1 error generated.
error: command 'gcc' failed with exit status 1

on Mac with Python 3.6 Conda installation.

**Comment by akshaykgupta** [comment]
try CFLAGS="-stdlib=libc++" python setup.py install

**Comment by vyraun** [comment]
@akshaykgupta thanks, but still getting the error:

MeCab_wrap.cxx:2987:10: fatal error: 'stdexcept.h' file not found
#include <stdexcept.h>
         ^~~~~~~~~~~~~
3 warnings and 1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by akshaykgupta** [comment]
sorry try it with single quotes CFLAGS='-stdlib=libc++'

**Comment by vyraun** [comment]
Didn't work, same error

**Comment by 91ns** [comment]
Same here

**Comment by gvskalyan** [comment]
I think you can try this 
sudo apt install mecab libmecab-dev mecab-ipadic-utf8 git make curl xz-utils file
as mentioned [here](https://github.com/neologd/mecab-ipadic-neologd#examples)

and point it to /usr/bin/mecab instead of bin/mecab in LASER directory
Hope this works

**Comment by ajkl** [comment]
This helped me -- http://taku910.github.io/mecab/#install
Also there is a hidden gem here :) -- https://github.com/facebookresearch/LASER/blob/master/install_external_tools.sh
Refer this on the right way to run configure for mecab and dictionary to install them in tools-external

**Comment by hoschwenk** [comment]
Installing mecab seems to be a real pain, but unfortunately, I can't support you with this 3rd party software. The next version of LASER will very likely use another approach for tokenisation, for instance sentence piece as mentionned above.
