### ISSUE TITLE
some confusions

### ISSUE THREAD

**Issue by leileilin** [facebookresearch/LASER#180]
hey man.
i have read source/embed.py, i have used embed.sh, and i test the inputfile value in source/embed.py, but i dont find the value of inputfile in embed.sh command i used.
any one can tell me what cause that?
thank you.

**Comment by hoschwenk** [comment]
The example in tasks/emebd/embed.sh should be called wit h3 arguments, e.g.
./emebd.sh  text-input.fr   fr    binary-embedding.fr.

The python program source/embed.py reads the text from stdin, e.g.
cat text-input.txt | python3 ${LASER}/source/embed.py ...

**Comment by leileilin** [comment]
> The example in tasks/emebd/embed.sh should be called wit h3 arguments, e.g.
> ./emebd.sh text-input.fr fr binary-embedding.fr.
> 
> The python program source/embed.py reads the text from stdin, e.g.
> cat text-input.txt | python3 ${LASER}/source/embed.py ...

thank you man.
i have done what i want, But I'm sorry I forgot to close the problem.
