### ISSUE TITLE
Kurdish issue

### ISSUE THREAD

**Issue by Sarchia** [facebookresearch/LASER#181]
Hello,

I noticed that Kurdish is only available as one language in this library. You may know, Kurdish is a macro language and consists of three main dialects/languages; Northern Kurdish (Kurmanji), Central Kurdish (Sorani), and Southern Kurdish.

Most Kurdish texts online are written in Kurdish (Kurmanji) (ku + kmr) and Kurdish (Sorani) (ckb).
I suggest adding both Kurmanji and Sorani as two languages. Note that Kurmanji uses the Latin script and Sorani uses the Arabic script.

A few months ago, we fixed this problem with Tatoeba too. Now it supports the three dialects of Kurdish.

**Comment by hoschwenk** [comment]
Hello,
Thanks a lot for these detailed information on Kurdish - this is very useful !
We will try to support the different dialects/version of Kurdish in the next version of LASER.

The current version of LASER was trained only a very small amount of Kurdish, we don't expect that its performance is as good as for other well-resourced languages , e.g. Spanish, Russian or Chinese.
