### ISSUE TITLE
How can I load encoder before embedding.

### ISSUE THREAD

**Issue by leileilin** [facebookresearch/LASER#182]
I have test the embedding time, it is too long for me. Anyone can tell me how to load encoder before embedding.
thank you.

**Comment by hoschwenk** [comment]
the program embed.py can process many input lines at once in batch mode. This is much faster than processing line by line. In that case, the encoder is loaded only once at beginning.
If you want to use the encoder in your own code, I recommend that you have a look at embed.py and use the same functionality.

**Comment by leileilin** [comment]
> the program embed.py can process many input lines at once in batch mode. This is much faster than processing line by line. In that case, the encoder is loaded only once at beginning.
> If you want to use the encoder in your own code, I recommend that you have a look at embed.py and use the same functionality.

thank you man.
i have done what i want, But I'm sorry, I forgot to close the problem.
