### ISSUE TITLE
Could you please provide a dumped version of the CCMatrix?

### ISSUE THREAD

**Issue by ChenzhengUESTC** [facebookresearch/LASER#183]
We only need the CCMatrix, however, the script “dl_cc_matrix.py” will download the whole CCNet, which is too big for my network bandwidth.

So , it'll be great If you could provide a dumped version of the CCMatrix.

**Comment by hoschwenk** [comment]
we are aware that the download procedure for CCMatrix takes a lot of time and resources, but unfortunately, we can not distribute directly the bitexts.
