### ISSUE TITLE
ccmatrix bitexts don't match

### ISSUE THREAD

**Issue by jorgtied** [facebookresearch/LASER#184]
Thanks for providing the download script but I still have trouble fetching the data.
After patiently waiting for the download to finish and fixing issues with newline characters and malformed Unicode I now get bitexts that do not match in the number of lines when running finalize:

```
      64612 data/v1.0.0/bitext/bn-la/bn.txt
      58796 data/v1.0.0/bitext/bn-la/la.txt
    6483349 data/v1.0.0/bitext/cs-lt/cs.txt
    6513655 data/v1.0.0/bitext/cs-lt/lt.txt
    2011563 data/v1.0.0/bitext/cs-mk/cs.txt
    2031690 data/v1.0.0/bitext/cs-mk/mk.txt
   12582027 data/v1.0.0/bitext/cs-tr/cs.txt
   11983102 data/v1.0.0/bitext/cs-tr/tr.txt
    1146006 data/v1.0.0/bitext/da-is/da.txt
    1151880 data/v1.0.0/bitext/da-is/is.txt
...
```

The numbers are close but none of them is the same. I wonder whether anyone already succeeded to actually download and compile the dataset with the provided script? Thanks for any further hints on getting this done.

**Comment by gwenzek** [comment]
I recommend using http://data.statmt.org/cc-matrix/ directly now that it is available.
