### ISSUE TITLE
pip3 install cc_net not working 

### ISSUE THREAD

**Issue by BeaLove** [facebookresearch/LASER#189]
Hi, hoping to use a subset of ccmatrix for research, but running into issues even before downloading:

from the README running pip3 install cc_net returns this:

ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
cc-net depends on kenlm@ git+https://github.com/kpu/kenlm.git@master 

installing that package (kenlm) makes no difference. Any suggestions?

**Comment by jgcb00** [comment]
same issue resolve with : 
pip install --no-deps cc_net
pip install cc_net

**Comment by gwenzek** [comment]
you need to clone cc_net locally and install from there.

but I recommend using http://data.statmt.org/cc-matrix/ directly instead of re-running the pipeline yourself which is very long

**Comment by gordicaleksa** [comment]
`pip3 install git+https://github.com/facebookresearch/cc_net.git` this one worked for me
