### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by jaremjs** [facebookresearch/LASER#193]
first time using LASER, trying to create embeddings from tatoeba data, getting these errors when I try to run:

ModuleNotFoundError: No module named 'transliterate'

...

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp4p3sxtv8/bpe'

I ran the install .sh scripts before use, but it was still missing dependencies, so I installed numpy, torch, and fastBPE with pip

What can I do to get the setup done properly here?

**Comment by NomadXD** [comment]
@jaremjs you can install it using `pip install transliterate`.
