### ISSUE TITLE
Cannot import name 'Token' from 'text_processing'

### ISSUE THREAD

**Issue by steventan0110** [facebookresearch/LASER#194]
Hi,

I'm trying to use the embed.py file and I cannot figure out how to solve the package import issue resulted by 
`from text_processing import Token, BPEfastApply`

I have used `pip install text_processing` but the installed package has no Token or BPEfastApply inside. I'm wondering if anyone can point me to the correct package to install here? Thanks,

**Comment by ZJaume** [comment]
Same issue, the tools path changed its name to lib. Changing this line:
```python
sys.path.append(LASER + '/source/tools')
```
by
```python
sys.path.append(LASER + '/source/lib')
```

solved the problem for me in `mine_bitexts.py`

**Comment by steventan0110** [comment]
Thanks for pointing out! I thought text processing is some third party tool from pip, didn't notice it's in lib folder.
