### ISSUE TITLE
https://data.statmt.org/cc-matrix/ is down?

### ISSUE THREAD

**Issue by alirezamshi** [facebookresearch/LASER#195]
Hi,

I tried to download cc-matrix data, but it seems that the website is down. Can you please check it?

Thanks.

**Comment by AlAntonov** [comment]
Hi, statmt is down today.
But you can get cc-matrix from opus https://opus.nlpl.eu/CCMatrix.php

**Comment by solutiongeek2022** [comment]
I am troubled with the same problems, including unused cc-matrix, the scores always change from 70 to 80, I can not solve it!
Here are the status examples:
https://www.laserchina.com/
https://www.laserchina.com/3d-printer/

**Comment by heffernankevin** [comment]
Just checked and cc-matrix data is currently up (https://data.statmt.org/cc-matrix/).
