### ISSUE TITLE
Any idea how to apply it for cutomized named entity recognition , eg. extraction of crime location from crime articles.

### ISSUE THREAD

**Issue by prashant334** [facebookresearch/LASER#2]

**Comment by hoschwenk** [comment]
Hello,
thanks for your interest in my work.
LASER provides sentence embeddings with the property that sentences with similar meaning, in the same or a different language, are close in the embedding space (according to cosine distance).
Generally speaking, LASER can be used to mine for texts which cover similar stories than a query.
However, the LASER embeddings are not meant to search for sentences which match specific named entities.
I hope that this helps.
