### ISSUE TITLE
Missing files for xnli.sh

### ISSUE THREAD

**Issue by webersab** [facebookresearch/LASER#20]
I tried running xnli.sh to replicate the XNLI results and got the following errors: 

LASER: training and evaluation for XNLI
 - loading encoder /group/project/s1782911/LASER/models/bilstm.93langs.2018-12-26.pt

Processing train:
 - Tokenizer: xnli.train.prem.tok.en exists already
 - fast BPE: processing xnli.train.prem.tok.en
 - Encoder: xnli.train.prem.bpe.en to xnli.train.prem.enc.en
Traceback (most recent call last):
  File "xnli.py", line 91, in <module>
    buffer_size=args.buffer_size) 
  File "/group/project/s1782911/LASER/source/embed.py", line 295, in EncodeFile
    fin = open(inp_fname, 'r') if len(inp_fname) > 0 else sys.stdin
FileNotFoundError: [Errno 2] No such file or directory: 'embed/xnli.train.prem.bpe.en'

Training the classifier (see embed/xnli.log)
Traceback (most recent call last):
  File "/group/project/s1782911/LASER/source/nli.py", line 228, in <module>
    dim=args.dim, bsize=args.bsize, shuffle=True)
  File "/group/project/s1782911/LASER/source/nli.py", line 36, in LoadDataNLI
    x = np.fromfile(fn1, dtype=np.float32, count=-1)
FileNotFoundError: [Errno 2] No such file or directory: 'embed/xnli.train.prem.enc.en'

Do you have an idea what might cause these errors and what I can do about them?
Thanks in advance!

**Comment by hoschwenk** [comment]
This is probably caused by the wrong path to fastBPE. This was resoloved in #9 .
Please pull the current source
