### ISSUE TITLE
How to set everything up for a translation from a given language ex: Albanian to English

### ISSUE THREAD

**Issue by fatjoni** [facebookresearch/LASER#202]
I am really hyped from the progress meta has made in this much needed offer. 

Regardless my background in coding etc i cannot work my way around how these tools work with each other to be able to set everything up for translation from albanian to english.

I managed to encode a sentence in albanian but that was all, dont know any there is no resource in the internet explaining what should be done next.

**Comment by heffernankevin** [comment]
Hi @fatjoni! The encoders in this repository are primarily intended for embedding sentences. However, if you would like to perform translation tasks using the NLLB model, you can follow the README from the nllb branch within the fairseq repository [here](https://github.com/facebookresearch/fairseq/tree/nllb). There is also [this youtube video tutorial](https://www.youtube.com/watch?v=N1oNQcunK6o) which you may find helpful. Hope this helps!
