### ISSUE TITLE
Embedder is not working with LASER3.

### ISSUE THREAD

**Issue by mahendra-gehlot** [facebookresearch/LASER#203]
I am trying to generate embedding with newly released LASER3 in google colab.

`! /bin/bash ./laser/tasks/embed/embed.sh ./input_text.txt ./output_2.bin ind_Latn`

<img width="790" alt="Screenshot 2022-07-11 at 9 42 35 AM" src="https://user-images.githubusercontent.com/26670521/178187428-b9aa1419-6133-4181-b4c1-941f7674fe07.png">

Although my input_text.txt contains 100s of lines of text to encode but, output showing 0 embeddings. 

May anybody help ?

**Comment by heffernankevin** [comment]
Hi @mahendra-gehlot. Can you try pulling and re-running your above command? It may have been the case that there was an additional package needed (i.e. `pip install transliterate`).

**Comment by mahendra-gehlot** [comment]
Thanks @heffernankevin , Now its working as intended.
