### ISSUE TITLE
.enc and .candidates.tsv

### ISSUE THREAD

**Issue by guangyuli-uoe** [facebookresearch/LASER#209]
hi,

when i tried to run bucc task,
there are two errors,

what is .enc. file and what is candidates.tsv file ?

FileNotFoundError: [Errno 2] No such file or directory: './embed/bucc2018.fr-en.train.candidates.tsv'
FileNotFoundError: [Errno 2] No such file or directory: './embed/bucc2018.fr-en.train.enc.fr'

**Comment by heffernankevin** [comment]
The `.enc` file contains the embeddings, and the `candidates.tsv` contains the alignments. Can you try the following:

1.  remove the `embed` directory
2. remove any generated log file such as `LASER/tasks/bucc/bucc2018*.log`
3. `git pull`
4. re-run `LASER/tasks/bucc/bucc.sh`

**Comment by heffernankevin** [comment]
@guangyuli-uoe were you able to run the bucc task successfully?

**Comment by heffernankevin** [comment]
Closing as user reported being able to run script successfully on laptop (https://github.com/facebookresearch/LASER/issues/212#issuecomment-1191933581). Please re-open if the issue persists.
