### ISSUE TITLE
LASER: calculation of sentence embeddings:        (  Temporary file error.   )

### ISSUE THREAD

**Issue by MFarhatUllah** [facebookresearch/LASER#21]
Hello LASER Team!
I try to run the "Sentence Embedding for text files" for fra language but it gives me the following error. may you please guide me....

command :::::>        ./embed.sh ${LASER}/data/tatoeba/v1/tatoeba.fra-eng.fra fr my_embeddings.raw

 - Encoder: loading /home/farhat/LASER/models/bilstm.93langs.2018-12-26.pt
 - Tokenizer:  in language fr  
 - fast BPE: processing tok
 - Encoder: bpe to my_embeddings.raw
Traceback (most recent call last):
  File "/home/farhat/LASER/source/embed.py", line 364, in <module>
    buffer_size=args.buffer_size) 
  File "/home/farhat/LASER/source/embed.py", line 295, in EncodeFile
    fin = open(inp_fname, 'r') if len(inp_fname) > 0 else sys.stdin
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp5mjbrkfz/bpe'

**Comment by hoschwenk** [comment]
This is caused by a missing path to fastBPE and was corrected in #9 
Please pull the current source and it should work.
