### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by guangyuli-uoe** [facebookresearch/LASER#210]
hi,

when i tried to run bucc task,

Processing BUCC data in .
2022-07-19 15:46:23,944 | INFO | embed | loading encoder: /Users/liguangyu/LASER/models/bilstm.93langs.2018-12-26.pt
./bucc.sh: line 82: 78886 Broken pipe: 13         cat ${txt}
     78887 Segmentation fault: 11  | python3 ${LASER}/source/embed.py --encoder ${encoder} --token-lang ${ll} --bpe-codes ${bpe_codes} --output ${enc} --verbose
2022-07-19 15:46:25,718 | INFO | embed | loading encoder: /Users/liguangyu/LASER/models/bilstm.93langs.2018-12-26.pt
./bucc.sh: line 82: 78890 Broken pipe: 13         cat ${txt}
     78891 Segmentation fault: 11  | python3 ${LASER}/source/embed.py --encoder ${encoder} --token-lang ${ll} --bpe-codes ${bpe_codes} --output ${enc} --verbose
/Users/liguangyu/LASER/source/mine_bitexts.py:224: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if args.retrieval is not 'bwd':
/Users/liguangyu/LASER/source/mine_bitexts.py:230: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if args.retrieval is not 'fwd':

**Comment by heffernankevin** [comment]
Closing issue as user reported no more segmentation faults after upgrading the pytorch version (see comment https://github.com/facebookresearch/LASER/issues/212#issuecomment-1190334968).
