### ISSUE TITLE
embed task stops at preprocessing

### ISSUE THREAD

**Issue by ruoyuxie** [facebookresearch/LASER#213]
Hi, I keep having this issue and am not sure where went wrong. Can anyone take a look at this? 

<img width="939" alt="Screen Shot 2022-08-04 at 1 27 31 AM" src="https://user-images.githubusercontent.com/76230052/182770335-03525ea7-adf6-4ea3-b7db-a19c858683df.png">

**Comment by heffernankevin** [comment]
Hi @ruoyuxyz, can you try upgrading to python >= 3.7?

**Comment by ruoyuxie** [comment]
Thank you so much for the help! python==3.7.7 works!
