### ISSUE TITLE
LASER 3 eng_Latn encoder model checkpoint link is broken

### ISSUE THREAD

**Issue by jaygala24** [facebookresearch/LASER#216]
Hi,

I hope you're doing well. I was trying to download the LASER 3 `eng_Latn` for one of my experiments and it seems the link is broken and not active anymore. Can you please take a look and update the link for the checkpoint?

**Comment by heffernankevin** [comment]
Hi @jaygala24, `eng_Latn` is not listed as [one of the supported LASER3 models](https://github.com/facebookresearch/LASER/tree/main/nllb) as it is already supported by the LASER2 model (`laser2.{pt,spm,cvocab}`). You can use this one :)

**Comment by jaygala24** [comment]
Hi @heffernankevin, thanks for the clarification. I'll check the LASER2 model for my use case.
