### ISSUE TITLE
'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by Islanna** [facebookresearch/LASER#22]
Hi!
I've tried to calculate sentence embeddings for a file in Russian language and failed with this error: `'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)`

The problem is that the data is UTF-8 encoded and default python `open` function doesn't support non-ASCII characters.

**Comment by Islanna** [comment]
Fxd it locally with changing `open(inp_fname)` to `codecs.open(inp_fname, encoding='utf-8')`

**Comment by hoschwenk** [comment]
Hello,
this is strange since we process Russian in XNLI without any problem.
Of course, all the file reading should be done in UTF-8 encoding.
For some reason, your reader defaults to 'ascii' which obviously can't handle all the 93 languages.

**Comment by hoschwenk** [comment]
In Python3 open(...,encoding='utf-8') should work too.
I'll update the code accordingly shortly.
Thanks for spotting this !
