### ISSUE TITLE
Sentence Embedding Reads No Input

### ISSUE THREAD

**Issue by prasunshrestha** [facebookresearch/LASER#221]
I want to calculate sentence embeddings of a text file, so I followed the code [as instructed
](https://github.com/facebookresearch/LASER/tree/main/tasks/embed). However, the encoder doesn't read any sentence from the text file. I made sure the file wasn't corrupted but to no avail. Here is the error message I get:

 - Encoder: loading [redacted]/laser/models/wmt22/laser2.pt
 - SPM: processing sample_input.txt  
 - Encoder: spm to sample_input.bin
 - Encoder: 0 sentences in 0s

Where could I have gone wrong? Thank you!

**Comment by heffernankevin** [comment]
@prasunshrestha could you try: `pip install transliterate` and then re-embedding? Sometimes this library is missing which causes issues.

**Comment by prasunshrestha** [comment]
Thanks, Kevin! I ended up re-doing the whole installation process from the start, and it worked. Perhaps, what you suggested might have done the trick.
