### ISSUE TITLE
how to get the sentence embedding using Librivox S2S?

### ISSUE THREAD

**Issue by zhhao1** [facebookresearch/LASER#224]
Librivox S2S only give the mined corpora. I want to get the speech sentence embedding using the fine-tuned XLSR. However, i can find the model described in paper. I was wondering if you have any plans to make this model public. 
Looking forward to your reply.

**Comment by heffernankevin** [comment]
Hi @zhhao1! You can find the models, along with instructions on how to embed using them [here](https://github.com/facebookresearch/fairseq/blob/ust/examples/speech_matrix/speech_laser_encoders.md).

**Comment by zhhao1** [comment]
> Hi @zhhao1! You can find the models, along with instructions on how to embed using them [here](https://github.com/facebookresearch/fairseq/blob/ust/examples/speech_matrix/speech_laser_encoders.md).

Thanks for your answer, and it helps a lot.
