### ISSUE TITLE
embed_sentences Path parameters

### ISSUE THREAD

**Issue by julianpollmann** [facebookresearch/LASER#231]
embed.py `embed_sentences()` takes a `pathlib.Path()` for some parameters (e.g. [ifname](https://github.com/facebookresearch/LASER/blob/main/source/embed.py#L468)), passing a Path/PosixPath will result in errors.

## Steps to reproduce:
    embed.embed_sentences(
        ifname=Path("some/overlaps/path.en"),
        encoder=encoder_model,
        token_lang=token_lang,
        spm_model=Path("spm/model/path/laser2.spm")),
        output=Path("some/output/path.emb"),
        verbose=True,
    )

This leads to following error:
`can only concatenate str (not "PosixPath") to str`
caused by passing a [Path to Token()](https://github.com/facebookresearch/LASER/blob/main/source/embed.py#L511) and running a [subprocess with this Path](https://github.com/facebookresearch/LASER/blob/main/source/lib/text_processing.py#L101).

Python 3.10.9
Laser latest

**Comment by heffernankevin** [comment]
Hi @julianpollmann, just commented on the PR!
