### ISSUE TITLE
CCMatrix Data download

### ISSUE THREAD

**Issue by yangyang0202** [facebookresearch/LASER#233]
Hi,When I download data from https://dl.fbaipublicfiles.com/laser/CCMatrix/v1.0.0 generate the following. Gz, but when I open this file to see the inside of the data, found that is empty, what is the cause of this? Is it the Internet?
![image](https://github.com/facebookresearch/LASER/assets/66658591/7c7b9a86-5c6f-4e99-a452-e97e55ccb091)
![image](https://github.com/facebookresearch/LASER/assets/66658591/52f12f89-9805-413e-8811-40e862f416f4)

**Comment by yangyang0202** [comment]
When I re-executed the python dl_cc_matrix.py dl -o data -v v1.0.0 command, I found that the data should have been re-downloaded rather than continued

**Comment by heffernankevin** [comment]
Hi @yangyang0202! Just double-checking if this solved your issue?

**Comment by heffernankevin** [comment]
Closing for now. Please re-open if the issue persists!
