### ISSUE TITLE
models as onnx files

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/LASER#24]
Hello
Looks like today pretrained models are in pythorch pt formats : 
"bilstm.eparl21.2018-11-19.pt"  
"bilstm.93langs.2018-12-26.pt" 
Would it be possible to also offer it in onnx format : 
https://onnx.ai
? 
Kind

**Comment by hoschwenk** [comment]
Hello,
thanks for the proposal. We currently don't have the encoders in onnx format, but we will look into this.
