### ISSUE TITLE
The included Dockerfile and associated Flask app is out of date in multiple ways.

### ISSUE THREAD

**Issue by andy-weinstein** [facebookresearch/LASER#245]
I slogged through this and I have a working Dockerfile and a new Flask app to go with it.
I don't have much time to deal with making a pull request and it's not clear to me if the pull requests are being integrated.
I am watching this repository, if you want me to help you please comment and I'll try to be responsive.
If there's demand and a chance that the pull request will be integrated, I'll do my best to help.

**Comment by avidale** [comment]
Hi @andy-weinstein !
There is a chance that a pull request will be integrated, especially if you are willing to iterate on it. 
The demand is not huge, but it seems some people are trying to use the dockerized app (e.g. the issue #240), so updating it doesn't look like a totally useless idea.
