### ISSUE TITLE
LASER3 encoders for English? (and other high res langs)

### ISSUE THREAD

**Issue by gordicaleksa** [facebookresearch/LASER#247]
Hi!

Wondering where do I find the LASER3 encoders for English, the download_models.sh script doesn't seem to support any of the high resource languages? Am I missing something out here?

Thank you!

**Comment by gordicaleksa** [comment]
I assume we should use LASER2 checkpoints for English, German, etc.? (the teacher models?)

**Comment by heffernankevin** [comment]
Hi @gordicaleksa! Yes you are correct! For high-resource languages such as English, German and [others](https://github.com/facebookresearch/LASER/#supported-languages), you can use the LASER2 model. However, if there is a language-specific LASER3 model available from [the list of available LASER3 encoders](https://github.com/facebookresearch/LASER/blob/main/nllb/README.md#list-of-available-laser3-encoders), you can go for that. Hope this helps!
