### ISSUE TITLE
Sentence embeddings – code typo

### ISSUE THREAD

**Issue by suissemaxx** [facebookresearch/LASER#25]
In the README.md **«LASER: calculation of sentence embeddings»** seems to be a small code typo:

Shouldn't this: 

`bash ./embed.sh INPUT-FILE LANGUGAE OUTPUT-FILE`

be this? 

`bash ./embed.sh INPUT-FILE LANGUAGE OUTPUT-FILE`

By the way: Thanks very much for sharing LASER! Much appreciated.

**Comment by hoschwenk** [comment]
thanks, I'll correct this type
