### ISSUE TITLE
SPM models not available

### ISSUE THREAD

**Issue by tbst730** [facebookresearch/LASER#250]
Hi, I noticed that many [available LASER3 encoders](https://github.com/facebookresearch/LASER/blob/main/nllb/README.md#list-of-available-laser3-encoders) don't have a downloadable SPM model. Is it true that only languages listed in `spm_langs` in https://github.com/facebookresearch/LASER/blob/main/nllb/download_models.sh have an SPM model? How should I encoder other languages without SPM? Thank you!

**Comment by heffernankevin** [comment]
Hi @tbst730! Yes, only a subset of the LASER3 encoders had their own SPM model. Otherwise, they were trained with the LASER2 spm. In the [embed script](https://github.com/facebookresearch/LASER/blob/main/tasks/embed/embed.sh) this is handled for you. 

Hope this helps!

**Comment by tbst730** [comment]
Hi @heffernankevin Thank you so much for the reply! That answers my question.
