### ISSUE TITLE
How can I parallelize LASER embeddings?

### ISSUE THREAD

**Issue by prasunshrestha** [facebookresearch/LASER#278]
I am using this code:

```
from laser_encoders import LaserEncoderPipeline
encoder = LaserEncoderPipeline(laser="laser2")
embeddings = encoder.encode_sentences(text)
```
`text` is a numpy array of texts, and `laser2` suffices my use case. How can I parallelize the embeddings, if at all? I am running a notebook instance with limited resources and no GPU support (`ml.t3.xlarge`). I have tried the following two (`ThreadPoolExecutor` and `multiprocessing`) to parallelize, but gains have been marginal:

```
# a function to encode a chunk of sentences
def encode_chunk(chunk):
    # Import the model locally for each thread
    encoder = LaserEncoderPipeline(laser="laser2")
    return encoder.encode_sentences(chunk)

# split the numpy array into five chunks
text_chunks = np.array_split(text, 5)

# create a ThreadPoolExecutor with 5 threads
with ThreadPoolExecutor(max_workers=5) as executor:
    # Map the chunks to the encode_chunk function
    embeddings_chunks = list(executor.map(encode_chunk, text_chunks))

# concatenate the embeddings from the chunks
embeddings = np.concatenate(embeddings_chunks)
```

```
# a function to encode a chunk of sentences
def encode_chunk(chunk):
    encoder = LaserEncoderPipeline(laser="laser2")
    return encoder.encode_sentences(chunk)

# split the numpy array into five chunks
text_chunks = np.array_split(text, 5)

# create a multiprocessing Pool with 5 processes
with Pool(processes=5) as pool:
    # Map the chunks to the encode_chunk function
    embeddings_chunks = pool.map(encode_chunk, text_chunks)

# concatenate the embeddings from the chunks
embeddings = np.concatenate(embeddings_chunks)
```

I would very much appreciate any help on this. Thank you in advance!

**Comment by avidale** [comment]
I would suggest you first check the CPU utilization: when embedding on CPU, there is high chance that your cores already well utilized (Pytorch usually takes a good care of it; please take a look [here](https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html)), and more parallelization won't help. This would explain the small gains from parallelization.

Another issue with your code is that for relative small chunks, initializing the model (`encoder = LaserEncoderPipeline(laser="laser2")`) might take even more time than actual embedding of texts (`encoder.encode_sentences(chunk)`). So I won't be surprised if a multiprocessing version is actually even slower than the default one. .

**Comment by avidale** [comment]
Ultimately, to speed up the computation, I recommend getting access to GPU (and make sure that you specify the batch size that leads to maximal utilization of the GPU, without causing out-of-memory errors). 

If this is infeasible, you may want to consider another sentence encoder which is less resource-consuming (which one to choose, depends on your use case). And by the way, please checkout [SONAR](https://github.com/facebookresearch/SONAR): it is a newer and better generation of LASER models (but not necessarily faster).

**Comment by prasunshrestha** [comment]
This is helpful; thank you for your reply, @avidale! I have had instances where the multiprocessing was slower than the baseline, so you might be right. I have a hard resource constraint, so GPU might not be feasible for me, unfortunately. I didn't know about SONAR before though, but this looks performing. Unlike LASER's BiLSTM, It is also transformed-based, so the runtime might be better.

**Comment by TheMightyRaider** [comment]
@prasunshrestha , Thanks for the neat example. I'm facing deadlock sort of issue when I store the model in the main thread instead of instantiating in the child processes.

```
from laser_encoders import LaserEncoderPipeline
import numpy as np

from multiprocessing import Pool

# ----> Declared the encoder in the main process
encoder = LaserEncoderPipeline(laser="laser2")

# a function to encode a chunk of sentences
def encode_chunk(chunk):
    emb = encoder.encode_sentences(["This is a sample text value."])
    print("Generated")
    return emb

# split the numpy array into five chunks
text_chunks = np.array_split(text, 5, axis=0)

# create a multiprocessing Pool with 5 processes
with Pool(processes=5) as pool:
    # Map the chunks to the encode_chunk function
    embeddings_chunks = pool.map(encode_chunk, text_chunks)

# concatenate the embeddings from the chunks
embeddings = np.concatenate(embeddings_chunks)
```

Any idea on how to fork the child processes safely?

**Comment by avidale** [comment]
@TheMightyRaider I don't think you need multiprocessing here: it adds an overhead to time and memory, and creates issues such as yours.
Typically, PyTorch uses OpenMP, which already distributes computation across multiple CPUs. If it doesn't fully utilize your CPUs, you can start by playing with its settings instead of spawning multiple processes and adjusting the batch size for the encoder. Ideally, it should lead to full CPU utilization without starting new processes.
You could start with the PyTorch docs on CPU threading: https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html

**Comment by TheMightyRaider** [comment]
Right, I'm essentially trying to benchmark the model speed based on its cores availability so for that I need to have a control on the cores it's allowed to use. I felt multiprocessing is one such way to achieve it.

Thanks for the reference @avidale
