### ISSUE TITLE
Cross-lingual Spam Detection

### ISSUE THREAD

**Issue by shoegazerstella** [facebookresearch/LASER#28]
Hi, I am working on a cross-lingual spam detection task. I have a dataset containing spam/non-spam sentences in different languages. My goal is to detect the spam no matter in which language it is. 
I was wondering how to approach this problem using LASER. I saw a number of examples but each of them require the language for training/testing the model. Is there a way I can generalize the usage of LASER for my purpose?

**Comment by hoschwenk** [comment]
Hi,
if your train a spam detection classifier on one English, let's say English, you should be able to apply it to any of the other supported languages. The encoder does not need to know the language of the input text. In the examples, we do specify the input language but this is only used by the tokenizer. 
You can probably use English for most of the languages without any impact on the results (the tokenizers handles punctuation and words like "don't" or "je n'ai pas faim".
Only for Chinese and Japanese, a segmentation is applied.
Hope this help !

**Comment by anassalamah** [comment]
So given that I have trained a classifier on English data and want to predict on Arabic data that has no labels, how would I do that? How can I load the saved model and apply it to a text file of documents and get the result so I can manually sample and validate?
Thanks!

**Comment by shoegazerstella** [comment]
Hey @anassalamah , 
Since the text is pre-processed using bpe, it is kind of agnostic about the language, so it should work IF arabic is one of the languages that is supported by laser. Check in the documentation for this.

**Comment by anassalamah** [comment]
Hey @shoegazerstella I understand that. Thanks for replying though 

I finally got it to give me the predictions by modifying the sent_classify file to take in the data without a label and return the actual predictions.
