### ISSUE TITLE
Unable to import LaserEncoderPipeline

### ISSUE THREAD

**Issue by sumedhan-r** [facebookresearch/LASER#280]
While calling LaserEncoderPipeline for the purpose of downstream NLP tasks, the first error that popped up was a ValueError, which stated 

mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed:  use default_factory

I asked the opinion of ChatGPT on the same and had got a code that slightly modified the line where the Config classes are declared.

After having made changes to all the respective Config related classes, I was getting another Error, namely ValidationError which stated

Object of unsupported type: '_MISSING_TYPE'
       full_key:
       reference_type=None
       object_type=None

Below are attached some screenshots related to the errors. Please look into this at the earliest.

<img width="765" alt="LASER 1_1" src="https://github.com/facebookresearch/LASER/assets/98798155/6ca604d4-6669-4b70-a41c-8aa25295e812">
<img width="753" alt="LASER 1_2" src="https://github.com/facebookresearch/LASER/assets/98798155/15a66420-de7a-4f82-93e7-2ebe3b4653ea">
<img width="802" alt="LASER 2_1" src="https://github.com/facebookresearch/LASER/assets/98798155/fe179c6b-8234-43e4-9020-2e7061cf91e3">
<img width="792" alt="LASER 2_2" src="https://github.com/facebookresearch/LASER/assets/98798155/bde01582-755b-46ef-85bf-1368e5c95a3d">
<img width="783" alt="LASER 3_1" src="https://github.com/facebookresearch/LASER/assets/98798155/d6b7e9c9-3c4e-417b-8204-82e784ed9a07">
<img width="810" alt="LASER 3_2" src="https://github.com/facebookresearch/LASER/assets/98798155/ba3f3601-ea05-4d61-8648-a0c12254bc5a">

**Comment by sumedhan-r** [comment]
The suggestion given by ChatGPT is as follows :

`@dataclass
class FairseqConfig(FairseqDataclass):
    common: CommonConfig = field(default_factory=CommonConfig)
    common_eval: CommonEvalConfig = field(default_factory=CommonEvalConfig)

# Rest of your code...`

**Comment by dpdeb** [comment]
I am getting this error too. I was able to recreate it in Python 3.11 right from the import statement:
`from laser_encoders import LaserEncoderPipeline` 

My sense is that ChatGPT's suggestion is on the right track. Specifically, there are a number of statements toward the end of  [fairseq/dataclass/configs.py](https://github.com/facebookresearch/fairseq/blob/main/fairseq/dataclass/configs.py) that assign a mutable type as a default. Assigning these using the pattern `field(default_factory=x)` makes these errors go away. 

It appears the dubious pattern is still used through the latest version of fairseq, v0.12.2, which was released in 2022.

**Comment by avidale** [comment]
@dpdeb @sumedhan-r can you please indicate the versions of `fairseq` and `omegaconf` that cause the error?

When I am installing all packages from scratch (see [this Colab notebook](https://colab.research.google.com/drive/19mYN1RCvabixR0qzDMAbjh04VwI4jrFa?usp=sharing) for repro), I get `fairseq-0.12.2`, `omegaconf-2.0.6` and `laser_encoders-0.0.1` installed by default, and they are working fine.

**Comment by TheHappyLemon** [comment]
So, I have got the same error:

raise ex  # set end OC_CAUSE=1 for full backtrace
    ^^^^^^^^
omegaconf.errors.ValidationError: Object of unsupported type: '_MISSING_TYPE'
        full_key:
        reference_type=None
        object_type=None
        
I also changed classes fairseq\dataclass\configs.py and hydra\conf\__init__.py to use default_factory and then received the error above. Has anyone come up with a fix? :)

**Comment by avidale** [comment]
@TheHappyLemon how can I reproduce your error?
Can you please share a Colab notebook or something that reproduces it?

**Comment by TheHappyLemon** [comment]
Error is reproduced with this environment:
conda create -n test_env python=3.11.8 anaconda

**Comment by avidale** [comment]
Apparently, Fairseq is not supporting Python 3.11 and newer versions; see e.g. https://github.com/facebookresearch/fairseq/issues/5191. 

Thus, there are 3 possible solutions for you:
1. Downgrade your Python to 3.10 or below
2. Fork Fairseq and fix the error (this pull request https://github.com/facebookresearch/fairseq/pull/5359 might be what you need)
3. Migrate from the LASER encoder (which uses Fairseq which has already become pretty stale) to the [SONAR encoder](https://github.com/facebookresearch/SONAR) (which performs better and is based on Fairseq2, a package that currently enjoys better support).
