### ISSUE TITLE
Code for BUCC task

### ISSUE THREAD

**Issue by ashim95** [facebookresearch/LASER#29]
Thank you for releasing the code. 

Any idea when the code for bitext mining is getting released?

**Comment by ashim95** [comment]
@hoschwenk Any idea on when the code for bitext mining will be out?

**Comment by hoschwenk** [comment]
I was away for 2 weeks. I'm working on it - it will be available within the next days.

**Comment by hoschwenk** [comment]
I've just uploaded the code.
Don't hesitate to contact me if you have further questions.
