### ISSUE TITLE
How to train with sent_classif.py

### ISSUE THREAD

**Issue by shoegazerstella** [facebookresearch/LASER#30]
Hi,
I am trying to understand how to organize my dataset for training using the `sent_classif.py` script.
I have 2 classes (spam/not-spam), and I have created the following files:

```
train_set_corpus.txt
val_set_corpus.txt
test_set_corpus.txt

train_set_labels.txt
val_set_labels.txt
test_set_labels.txt
```

The `XX_corpus.txt` files contain only the text, while the `XX_labels.txt` are the corresponding labels. First question: Is this correct? Should the files be splitted like that?

I have also encoded my labels as numerical since I encountered the error `ValueError: could not convert string to float: 'SPAM'`. So now I have binary labels.

I am launching the script as follows:

```
python3.6 sent_classif.py -s data/spam_dataset/laser_output/ -t train_set_corpus.txt -T train_set_labels.txt -d val_set_corpus.txt -D val_set_labels.txt -e test_set_corpus.txt -E test_set_labels.txt -g -1 -b /src/data/spam_dataset
```

But I have this error:

```
 - base directory: /src/data/spam_dataset
 - read 93957x1024 elements in train_set_corpus.txt
 - read 278471 labels [0,1] in train_set_labels.txt
Traceback (most recent call last):
  File "sent_classif.py", line 188, in <module>
    dim=args.dim, bsize=args.bsize, shuffle=True)
  File "sent_classif.py", line 41, in LoadData
    D = data_utils.TensorDataset(torch.from_numpy(x), torch.from_numpy(lbl))
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataset.py", line 36, in __init__
    assert all(tensors[0].size(0) == tensor.size(0) for tensor in tensors)
AssertionError
```

**Comment by shoegazerstella** [comment]
[UPDATE]

I managed to use embed.sh to extract the embeddings for my train, test and dev corpus.
I am now using `sent_classif.py` and it seems to be working, the training corpus are the embeddings and the labels are .txt files.

I just wanted to report a possible bug: 
I had this error:

```
- base directory: /src/data/spam_dataset
 - read 278521x1024 elements in train_set_emb
 - read 278521 labels [0,1] in train_set_labels.txt
 - read 14725x1024 elements in val_set_emb
 - read 14725 labels [0,1] in val_set_labels.txt
 - setting seed to 123456789
 - mlp 1024Traceback (most recent call last):
  File "sent_classif.py", line 202, in <module>
    nhid=args.nhid, dropout=args.dropout, gpu=args.gpu)
  File "sent_classif.py", line 57, in __init__
    if len(nhid) > 0:
TypeError: object of type 'int' has no len()
```

It refers to line 57 in sent_classif.py, I fixed it like this and the train started properly:

`if nhid > 0:`

**Comment by hoschwenk** [comment]
nhid can be a sequence of several values (to get a deep MLP).
The correct fix is (line 155ff)
parser.add_argument(                                                                                                     
    '--nhid', '-n', type=int, default=[0], nargs='+',                                                                    
    help="List of hidden layer(s) dimensions")        
I'll update this in the code.
BTW, you'll probably get better results using hidden layers.
Also, I recommend to rename your files so that they end with the  language ID,
this is used to loop over several files when testing (see the files for MLDoc)
