### ISSUE TITLE
Source code for system training

### ISSUE THREAD

**Issue by maxdel** [facebookresearch/LASER#31]
Hi! Could you please open source the code that was used to train full encoder-decoder system?

 It would be extremely helpful for those who work on improving embeddings itself and want to use your work as a starting point.

Thank you

**Comment by hoschwenk** [comment]
Hello,
Yes we plan to open-source the training code, but we still need to clean it up and make it easy to use.
Hopefully, it won't take too long ...

**Comment by loretoparisi** [comment]
👍

**Comment by hvingelby** [comment]
Any news on the clean-up process?

**Comment by guotong1988** [comment]
Have you release the source code for training?
If not, do you know some other code for sentence embedding?

**Comment by udhanMti** [comment]
Any news on the releasing of training code?
