### ISSUE TITLE
Question: Can we use LASER for sentence entailment?

### ISSUE THREAD

**Issue by rajasen2019** [facebookresearch/LASER#34]
I tried sentence embedding example, and I observed that it doesn't understand sentences with opposite meaning. 

Is there any way to tune it or use different models?

**Comment by hoschwenk** [comment]
Could you please specify what you mean with "it doesn't understand sentences with opposite meaning." ?
The system handles very well the XNLI task. This task consists in the classification of two sentence as "related", "neutral" or "opposite"

**Comment by rajasenpwc** [comment]
> Could you please specify what you mean with "it doesn't understand sentences with opposite meaning." ?

Like "I love Maths instead of English" and "I love English instead of Maths".
I used sentence encoder and tried to calculate the cosine similarity, unfortunately the result was 1.0

**Comment by hoschwenk** [comment]
Something must be wrong in your experiment. It is highly unlikely that the embeddings of two different sentences have a cosine of 1.0
I tried your example and I get a value of about 0.9

**Comment by rajasen2019** [comment]
used #32 
```

MODEL_DIR = f"{LASER}/models"
ENCODER_PATH = f"{MODEL_DIR}/bilstm.93langs.2018-12-26.pt"


encoder = SentenceEncoder(
        ENCODER_PATH,
        max_sentences=None,
        max_tokens=12000,
        sort_kind='mergesort',
        cpu=True)

sentences = [
    'I love Maths instead of English',
    'I love English instead of Maths'
]

embeddings = encoder.encode_sentences(sentences)
print(np.inner(embeddings, embeddings))

from scipy import spatial

dataSetI = embeddings[0]
dataSetII = embeddings[1]
result = 1 - spatial.distance.cosine(dataSetI, dataSetII)
print(result) # result 1.0
```

**Comment by hoschwenk** [comment]
This is not correct. You need to tokenize and perform BPE before calling encode_sentences().
In particular, without BPE, most of the "full words" are considered as unknown and are mapped to the same token. This explains why the two sentences end up being "identical".

Please see source/embed.py and tasks/embed/README.md
