### ISSUE TITLE
language translation

### ISSUE THREAD

**Issue by Stolaine** [facebookresearch/LASER#35]
how can i use LASER to translate english into hindi or vice versa ?

**Comment by hoschwenk** [comment]
The goal of LASER is not to perform MT, but to obtain a language independent sentence representation. There is no generative model (decoder) to create an output sequence.
However, you can train a sentence classifier or NLI system on English and then apply it to Hindi (or vice versa)

**Comment by gvskalyan** [comment]
`For completeness, we also provide results that include the use of Machine Translation (MT). This can be done in two ways: 1) translate the test data into English and apply the English NLI classifier, or 2) translate the English training data and train a language specific NLI classifier for each language. It should be stressed that we are not evaluating multilingual sentence embeddings anymore, but rather the quality of the MT system and a monolingual model. `

Though the goal is not to perform MT, the translation quality/performance can be viewed if the pretrained decoder is provided, else providing the code to train the seq2seq architecture will make easy to experiment with transformer/transformer variants.
