### ISSUE TITLE
Usage of an absolute address  in mldoc.sh

### ISSUE THREAD

**Issue by sedflix** [facebookresearch/LASER#36]
I think this should use some sort of env variable or something else. 
https://github.com/facebookresearch/LASER/blob/6e28dc3b838ed72c15d7e015ada8b06f9ace51a7/tasks/mldoc/mldoc.sh#L87

**Comment by hoschwenk** [comment]
Indeed, it should point to $LASER/tools-external/mecab
I'll correct this.
Thanks for spotting this error !
