### ISSUE TITLE
embed task: number of embedding more than given sentences

### ISSUE THREAD

**Issue by sedflix** [facebookresearch/LASER#37]
I used ` ./embed.sh ./es_tass1.txt es es_tass1.raw` to run the embedding example.
It executed successfully with the following info:
```
 - Encoder: loading /app//models/bilstm.93langs.2018-12-26.pt
 - Tokenizer:  in language es  
 - fast BPE: processing tok
 - Encoder: bpe to es_tass1.raw
 - Encoder: 7217 sentences in 6s
```
The encoder encoded the given 7217 sentences .

But while reading the raw embedding as per the script give [here](https://github.com/facebookresearch/LASER/tree/master/tasks/embed#output-format), I'm getting `7219` embeddings. 

What could be the possible reason for getting +2 number of embeddings?

**Comment by hoschwenk** [comment]
What is the file size of es_tass1.raw ?
You should get 1024 * 4 bytes for each encoded sentence

**Comment by sedflix** [comment]
```
~/p/d/v/L/t/embed> ls -l es_tass1.raw
-rw-r--r-- 1 root root 29560832 Feb 12 07:02 es_tass1.raw
```

**Comment by hoschwenk** [comment]
This is exactly 7217 x 1024 x 4, i.e. the encoding did correctly process and saved 7217 sentences.
Something must be wrong when reading the data with numpy.
What is the shape of X before the resize operation ?

**Comment by sedflix** [comment]
Oops sorry! I was reading es_tass.raw(it was prepared without removing "\n") rather than es_tass1.raw.
Thanks for such quick responses.
