### ISSUE TITLE
unseen words

### ISSUE THREAD

**Issue by Stolaine** [facebookresearch/LASER#38]
First of all thanks for providing LASER.
I am trying to get the embedding of some sentences in hindi.
The question is that - how the trained biLSTM model is handling an unseen word ?
if all the words in the sentence is new how the sentence embedding is calculated?

I understood following:-
BPE - encoder takes care of unknown words. for every word it tries to break the word into subwords. e.g. "loved" will be broken into "lov" and "ed" and "loving" will be broken into "lov" and "ing". So if a new word comes it breaks it into known sub words and gives the output regarding those sub-words

<img width="670" alt="bpe_example" src="https://user-images.githubusercontent.com/35038791/52625072-347d0b80-2ed6-11e9-80a3-6ee0b308ebb4.PNG">

correct me if i am wrong

**Comment by hoschwenk** [comment]
Yes, you are correct.
The same principle applies to sentences in Hindi.
The BPE vocabulary is multilingual and includes Hindi words and subwords.
