### ISSUE TITLE
Problems with replicating MLDoc results

### ISSUE THREAD

**Issue by PiotrCzapla** [facebookresearch/LASER#39]
Thank you for open sourcing your work. We are trying to test MLDoc zeroshort performance and simply running mldoc.sh does not reproduce the results. I've run them twice and got the same results that are far from expected:

| Train |   en  |   de  |   es  |   fr  |   it  |   ru  |   zh  |
|-------|-------|-------|-------|-------|-------|-------|-------|
|  en:  | 90.88 | 86.48 | 67.62 | 61.98 | 69.95 | 22.95 | 11.65 |
|  de:  | 73.23 | 92.90 | 77.23 | 74.05 | 72.30 | 24.80 |  9.93 |
|  es:  | 65.62 | 80.58 | 92.03 | 73.28 | 69.03 | 34.10 | 12.58 |
|  fr:  | 78.35 | 85.45 | 78.20 | 89.68 | 69.85 | 33.88 |  9.68 |
|  it:  | 73.93 | 84.58 | 79.23 | 76.73 | 84.03 | 34.48 | 11.83 |
|  ru:  | 57.33 | 63.78 | 45.80 | 52.78 | 51.15 | 66.08 | 36.28 |
|  zh:  | 26.15 | 28.13 | 21.88 | 29.33 | 30.58 | 34.38 | 75.62 |

Do you happen to have the original mldoc models stored somewhere? If so could you share them It would help us to debug the issue.

**Comment by hoschwenk** [comment]
Hmm, strange.
If I run the script, I get exactly the numbers in README.md and you should be able to get the same results (using PyTorch 1.0)
Your results on Chinese (and Russian) are very low. This is supecious. Could you please check the log files whether tokenization and BPE does run correctly.
Try to pull the current code. Issue #9 corrected a bug (fastBPE was not in the path.)

**Comment by hoschwenk** [comment]
May be something is wrong with the installation of the MLDoc files.
You should get ('wc -l' for English)
   1000   246123  1502857 MLDoc/mldoc.dev.en
    4000   951177  5813042 MLDoc/mldoc.test.en
    1000   237232  1449930 MLDoc/mldoc.train1000.en

**Comment by PiotrCzapla** [comment]
@hoschwenk, you are on to something. We have used the current version of MLDoc generation script (May 2018), and all clues suggest that you are using some older verision.

1. your scripts expect  labels as "C", "E", "G", while the MLDoc data set have them encoded as  'CCAT', 'ECAT', 'GCAT', 'MCAT'.  https://github.com/facebookresearch/MLDoc/blob/master/generate_documents.py#L40

2. You numbe of characters does not much mine, which are much higher even if I account for 1. My guess is that your MLDoc dataset has different text representation than the current one, as the current version of the scripts output text of the articles as Python text representation of UTF-8 encoded byte strings. Such encoding escape all non-ascii characters which makes the new MLDoc dataset character count much longer.  And it completly scrambles the Chinese and Russian if the encoding isn't reversed. Besides the reason why the MLDoc/generate_documents.py does that looks like an unintenional side effect.

Here is how first training example looks like in my data set:
```
$ head -n 1 MLDoc/mldoc.dev.zh                                                                                                                                          
CCAT	b' \xe3\x80\x94\xe8\xb7\xaf\xe9\x80\x8f\xe7\xa4\xbe\xe5\x8f\xb0\xe5\x8c\x9720\xe6\x97\xa5\xe9\x9b\xbb\xe3\x80\x95\xe3\x80\x80\xe3\x80\x80\xe5\x8f\xb0\xe7\x81  .... \x9b\xa4\xe8\xb5\xb0\xe9\xab\x98.\xef\xbc\x88\xe5\xae\x8c\xef\xbc\x89   (c) Reuters Limited 1997 '
```

I'm going to report an issue in MLDoc repository as well. I can try to fix the issue if you tell me what kind of format your script expcet. Should it be simple UTF-8 encoded tab separated CSV?

**Comment by hoschwenk** [comment]
Thanks for tracing the problem with MLDoc.
LASER expects all text input to be in UTF-8 encoding. MLDoc should also create UTF-8.
I'll change mldoc.sh so that it accepts the classes encoded in both ways.

**Comment by PiotrCzapla** [comment]
Thank you. Converting to UTF-8 fixed the issue and the results looks really good:
```
Accuracy matrix:
Train     en     de     es     fr     it     ru     zh
 en:    91.48  87.65  75.48  84.00  71.18  66.58  76.65
 de:    78.23  93.50  81.40  81.50  74.53  64.58  73.20
 es:    71.62  84.00  93.73  78.90  73.38  53.33  55.83
 fr:    81.30  88.75  80.12  90.85  72.58  67.35  79.40
 it:    74.33  83.53  80.58  79.78  84.48  66.45  63.35
 ru:    72.38  81.65  65.73  71.30  63.33  85.45  59.58
 zh:    74.98  81.35  72.20  73.28  70.08  66.23  88.30
```

I'm not sure if Xian Li is checking the issues in the github repository so it might take time to be fixed. I've created a PR with a fix.  Maybe you can point the Readme.md to either an older version of the script or my PR.

Thank you again for the quick response!
