### ISSUE TITLE
Pre-trained embeddings for En-Zh

### ISSUE THREAD

**Issue by zaemyung** [facebookresearch/LASER#4]
Hello,
Thanks for open-sourcing & maintaining this useful package. I've been using it well for gathering parallel sentences from Wikipedia.

I was wondering, would it be possible to make the pre-trained multilingual encoder model for Chinese and English (as used in the paper, "_Learning joint multilingual sentence representations with neural machine translation_") publicly available?

**Comment by hoschwenk** [comment]
Hello,
thanks for your interest in LASER.
we have developed new models for more languages which will include Chinese.
we have also improved the quality of the bitext extraction process.
Both will be available by the end of October.

**Comment by imeanu** [comment]
Hello,
Any progress on new release? I'm expecting Korean and Japanese support. :)
