### ISSUE TITLE
Error: Get BPE code in Chinese

### ISSUE THREAD

**Issue by JinmingZhao** [facebookresearch/LASER#41]
Hi,
I can't get bpe codes in Chinese:

./fast applybpe  data/embd/lcqmc.dev.prem.bpe.zh  data/embd/lcqmc.dev.prem.tok.zh LaserModel/models/93langs.fcodes  LaserModel/models/93langs.fvocab

will result error: 
Read 2369862597 words (73636 unique) from vocabulary file.
Loading codes from LaserModel/models/93langs.fcodes ...
Read 50000 codes from the codes file.
Loading vocabulary from data/embd/lcqmc.dev.prem.tok.zh ...
Read 328980 words (235 unique) from text file.
fast: fast.cc:486: void decompose(std::__cxx11::string, std::vector<std::__cxx11::basic_string<char> >&, const std::unordered_map<std::__cxx11::basic_string<char>, std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >&, const std::unordered_map<std::__cxx11::basic_string<char>, unsigned int>&, bool): Assertion `count == 1' failed.
fast: fast.cc:486: void decompose(std::__cxx11::string, std::vector<std::__cxx11::basic_string<char> >&, const std::unordered_map<std::__cxx11::basic_string<char>, std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >&, const std::unordered_map<std::__cxx11::basic_string<char>, unsigned int>&, bool): Assertion `count == 1' failed.
Aborted (core dumped)

But in english, it work well:
./fast applybpe  data/embd/mrpc.dev.prem.bpe.en data/embd/mrpc.dev.prem.tok.en LaserModel/models/93langs.fcodes LaserModel/models/93langs.fvocab 
Read 2369862597 words (73636 unique) from vocabulary file.
Loading codes from LaserModel/models/93langs.fcodes ...
Read 50000 codes from the codes file.
Loading vocabulary from /data/embd/mrpc.dev.prem.tok.en ...
Read 38776 words (7710 unique) from text file.
Applying BPE to data/embd/mrpc.dev.prem.tok.en ...
Modified 38776 words from text file.

Thanks.

**Comment by hoschwenk** [comment]
Did you segment the Chinese texts before applying BPE ?
Or maybe there's a invalid UTF-8 character in the text ?

**Comment by JinmingZhao** [comment]
Thank you very much,  the generated *tok* files are in 'iso-8859-1' character.

My solusion as below:

`def transfer2utf8_v2(filepath):
    f = open(filepath, 'rb')
    content = f.read()
    source_encoding = 'utf-8'
    try:
        content.decode('utf-8').encode('utf-8')
        source_encoding = 'utf-8'
    except:
        try:
            content.decode('gbk').encode('utf-8')
            source_encoding = 'gbk'
        except:
            try:
                content.decode('gb2312').encode('utf-8')
                source_encoding = 'gb2312'
            except:
                try:
                    content.decode('gb18030').encode('utf-8')
                    source_encoding = 'gb18030'
                except:
                    try:
                        content.decode('big5').encode('utf-8')
                        source_encoding = 'big5'
                    except:
                        try:
                            content.decode('iso-8859-1').encode('utf-8')
                            source_encoding = 'iso-8859-1'
                        except:
                            try:
                                content.decode('cp936').encode('utf-8')
                                source_encoding = 'cp936'
                            except:
                                print("***Error: Please try others!")
                                exit(0)
    f.close()
    print("The file encoding is {}".format(source_encoding))
    os.system("cp {} {}".format(filepath, filepath + '.temp'))
    temp_file = filepath + '.temp'
    with open(temp_file, 'r', encoding=source_encoding) as f1:
        content = f1.read()
    with open(filepath, 'w', encoding='utf-8') as f2:
        f2.write(content)
    os.system("rm {}".format(temp_file))
`

**Comment by hoschwenk** [comment]
LASER expects text to be encoded in UTF-8.
There is no need to write new python code, you can use the Unix tool "iconv" to convert the encoding of your text files.

**Comment by JinmingZhao** [comment]
I have tried the 'iconv' tool, but it doesn't work.  
The 'enca' and 'chardetect' tools can't detect the encording of the files.
However, iconv need the 'from-encoding' and 'target-encoding' information.

**Comment by hoschwenk** [comment]
Usually, one knows the encoding of the files - using a tool to guess it may be very dangerous and is very error prone. I would suggest to review you processing pipeline and handle all files in UTF-8.
