### ISSUE TITLE
Compute Document Embedding from Sentence Embeddings

### ISSUE THREAD

**Issue by akjindal53244** [facebookresearch/LASER#42]
Hi,

Thank you for amazing work!

We have a cross lingual document classification (Binary) use-case where each documents is more than 500 words and we have labelled data for 2 foreign languages along with English. Few Questions:

1.  How is document embeddings being computed currently? Does entire sequence get passed through biLSTM in one go? If that is true, can we compute it in a better way specially for documents since semantic representation of document might not be good enough while passing entire sequence?
2. Will training on combined multilingual data is any better than training on Only English data and then doing inference over other languages?
3. Do we have to pass any explicit encoding while calling `embed.sh` in case of languages like French and Spanish? I see default encoding is `utf-8`, Is there something I should be worried about as pointed out in https://github.com/facebookresearch/LASER/issues/39

TIA! :)

Regards,
Ashvini

**Comment by hoschwenk** [comment]
Hello,
here are my answers:
1) Embeddings are calculated for one line of text. It is up to you whether the line contains multiple sentences or not (separated by a "."). You can look at the code for MLDoc, we split long paragraphs into multiple lines at punctuation, calculate embeddings for each sentence and average them for the paragraph. This may work for your task, too. You can also try to simply process the whole line of 500 words or find a better way to combine multiple sentence emebddings..
2) training on multilingual data should work better: the model is likely to be more robust and you have more training data
3) Simply use UTF-8 for all texts. You should be also aware that embed.py expects the language ID. This is not used for the encoder but for tokenization, e.g. to handle French texts like "Je n'ai pas faim"
I propose that you adapt the example for the MLDoc task - you just need to change from 4 to 2 classes.
