### ISSUE TITLE
Similarity between Embeddings

### ISSUE THREAD

**Issue by simonefrancia** [facebookresearch/LASER#44]
Hi, 
I am trying to use LASER embedding in order to calculate similarity between sentences. I tried with inner product and results are not bad, but maybe others are better. 
What similarity would you recommend? 
Thanks

**Comment by hoschwenk** [comment]
Hi,
I would say that this depends on you application.
The cosine distance between two sentences should reflect quite well the linguistic similarity, in the same language or cross-lingual.
This can be further improved using a margin criterion as it is used in LASER for bitext mining (see tasks/bucc and reference [5] in the main README.md)
Which languages you are interested in ?

**Comment by simonefrancia** [comment]
I am doing a system that calculates similarity between two generic sentences. Languages of the two sentences are inputs of my system, and so I would like to apply a similarity/distance measure that reflects semantic similarity/distance between sentences of different languages. 
I would like to include all 93 languages in this system. 
Thanks

**Comment by bittlingmayer** [comment]
I'm using the following:
```
import numpy as np
def similarity(v1, v2):
    n1 = np.linalg.norm(v1)
    n2 = np.linalg.norm(v2)
    return np.dot(v1, v2) / n1 / n2
```

However, IMHO there needs to be length normalisation.  Otherwise, as input length grows, all output vectors start to approximate each other.

Meanwhile there are very short inputs that, by subjective human judgement, are perfect translations, but for which the vector similarity is solid (> 0.75), but not great.  For example, the word for *yes* in every language.

Besides that, there are the inherent properties of a single space.  So, an identity translation always has a high score.  For some purposes this could be normalised a bit too, eg by the Levenshtein similarity.

**Comment by hoschwenk** [comment]
Yes, it is advised to normalize the vectors (LASER uses faiss.normalize_L2() internally)  when using dot product, or cosine distance which is equivalent.
LASER was trained on sentences of at least 4 words. Such short sentences carry little linguistic information. It is expected that the performance degrades for shorter sentence or single words.

**Comment by bittlingmayer** [comment]
Was the 4-word min across all languages?  Seems like a char min is more agnostic to typology and orthography (agglutination, pro-drop, compounding, contractions).

And is it 4 words or 4 tokens (incl `,`, `:`, `?`...)?

de: `Trump: Besteht Selbstmordgefahr?` ~= it: `Trump: esiste il rischio di suicidio?`
en: `I am well, thanks.` ~= tr: `iyiyim, mersi`.

**Comment by bittlingmayer** [comment]
Since this isn't a bug per se, maybe we can just add your guidance to the README.

**Comment by hoschwenk** [comment]
We know that LSTMs are sensible to the length distribution of the training sequences.
This 4-word limit is just a heuristic to exclude sentences which are unlikely to improve the model.
LASER is a sentence embedding model and we assumed that "natural" sentences are longer than 1 or 2 words. Such short "sentences" can be probably better handled with multilingual word embeddings.
Indeed, the sentence length varies a lot among languages, as in your example: German uses very long compounds which can translate into multiple words in other languages.

**Comment by hoschwenk** [comment]
I will add a comment in the README that LASER is a sentence embeddings approach and that it can't be expected that the multilingual similarity distance is reliable for 1 or 2 word sequences.
Thanks a lot for your valuable feed-back.

**Comment by simonefrancia** [comment]
Thanks for your support!

**Comment by loretoparisi** [comment]
@hoschwenk I think a good point by @bittlingmayer is about languages where the embeddings space have less tokens for the same sentence representation: `en: I am well, thanks. ~= tr: iyiyim, mersi.`.
Now the tatoeba corpus is a sentence based corpus, that is a good base for training language models for tasks like language identification (FastText):

```
__label__ita Adesso datemi le chiavi.
__label__ara ياله من طفل محبب! يييي!
__label__eng You're a really bad bartender.
__label__epo En kiu hotelo vi restados?
__label__spa Él dijo haber perdido su vigor a los cuarenta.
__label__deu Heute ist Mittwoch. Ich lese gerade.
__label__eng I caught a glimpse of him from the bus.
__label__eng I advise you to do that today.
__label__jpn この歌の歌い方を教えてくれますか。
__label__deu Ich habe gewusst, dass ihr Tom nicht vergessen würdet.
```

so it could be worth to have the training part of LASER, in order that one could extend the model to shorter sentences,  document level corpora, etc.

**Comment by hoschwenk** [comment]
It is normal that the sentence length varies between languages, the typical example is German which uses very long compound words. LASER is trained on a variety of sentence, short one and long one, and it can handle this. Recently, I've tested very short sentences and it seems to work well.
I haven't tried single words and that's not the goal of LASER - there are other approaches arround for this. We explicitly focus on sentence representations which you can't get by simply combining word representations.

**Comment by hoschwenk** [comment]
We will also make available the training part of LASER, but you should be aware of several facts:
 - LASER embeddings are good since they are trained on millions of sentences in many languages at once. This requires computational resources which many people don't have (e.g. 2-3 days on several GPUs in parallel)
 - training on some thousands
 sentences of your favorite language will perform VERY POORLY !
   You need you to train them jointly with the other languages to benefit of similarities among the languages.

**Comment by hoschwenk** [comment]
With respect to documents, nothing prevent you from using LASER to embed very long sentences or paragraphs (for LASER an end of sentence point or other punctuation marks are characters like all the other ones).
But embeddings sections with many hundreds of words into a single vector is not expected to work very well what ever method you use, There is simply to much information

**Comment by loretoparisi** [comment]
@hoschwenk thank you very much for the details! I agree about training, indi developers could not be able to train on such expensive resources, and thank you for your  pre-trained models for this! Basically for training LASER should be trained from scratch on joint languages, maybe adding new languages if these are not present in the current model.
We are going to make a more intense test on short sentences (song lyrics sentence) in several language, and I will back with some results.
