### ISSUE TITLE
multi-gpu in embed.py

### ISSUE THREAD

**Issue by PersianNLPer** [facebookresearch/LASER#48]
Does embed.py support multi-gpu? I need to get the sentence embeddings of a rather large corpus (+40M sentences) and was looking into embed.py to see if it supports multi-gpu to speedup the process. But, it seems that currently it can run only on a single gpu. right? May I ask you if there is any script for this purpose?

Thank you,
Amin

**Comment by hoschwenk** [comment]
Hello,
Embed.py does not support multi gpu mode, but actually it is not needed. The solution is much easier:
- split your text files in N chunks (Unix "split")
- run embed.py in parallel on each one
- combine the embeddings
I'm using this recipe for all my large scale experiments (N=10M)
On the other hand, 40M sentences can be processed in 5-6 hours one a single recent GPU :-)
(this obviously depends on the sentence length)

**Comment by PersianNLPer** [comment]
Dear Holger,
thank you very much for the response. Well, I thought about this solution but then thought that you might already have a code which already handles this. I am now following your advise and encoded my whole corpus.

Thank you very much!

**Comment by PersianNLPer** [comment]
By the way, I think there is nothing more to discuss in this thread. So, I close it!

Thank you again,
Amin

**Comment by ajkl** [comment]
@hoschwenk embed.py does not take gpu id, I was wondering how you assign different embed runs for the splits on different gpus. Any pointers on your workflow there?

**Comment by ZenBel** [comment]
Would it be possible for you to share a template script for this?

Thanks,
Z
