### ISSUE TITLE
Computing sentence embeddings for other sentences

### ISSUE THREAD

**Issue by siddsach** [facebookresearch/LASER#5]
This is such a cool project, thanks for putting it out! I was wondering what the process is to compute our own embeddings on text. For example, if I have a list of sentences in Portuguese, what format do they need to be in and what do I need to do to compute their embeddings?

**Comment by hoschwenk** [comment]
Hello,
thanks for your interest in this tool.
You can easily calculate the embeddings for sentences in any of the supported languages.
To do so, I propose to have a look at tasks/similarity/sim.sh
You only need the lines
Tokenize YOUR_TEXT_FILE "pt"
Embed  YOUR_TEXT_FILE.tok.lc "pt" "eparl20kj" 2000 $gpu

set gpu=-1 to run on CPU or gpu=0 to run on GPU (faster !)

Let me know if you have further questions
