### ISSUE TITLE
Is it possible to fine-tune the LASER Encoder on End Task(for example classification) ? And Will it improve the performance ?

### ISSUE THREAD

**Issue by gourango01** [facebookresearch/LASER#50]

**Comment by hoschwenk** [comment]
We see it rather as an advantage that LASER embeddings that they perform well in several tasks without the need of fine tuning. In principle, fine-tuning has the potential to improve the performance on a specific task, but this is usually done for one language only (English). and may hurt the cross-lingual transfer performance.
We have not yet tried fine-tuning with LASER embedding, but we would of course be very interested in getting feed-back on such experiments.

**Comment by hoschwenk** [comment]
I'm closing this issue since there seems to be no more comments on it.
