### ISSUE TITLE
Running Laser line by line with TokenLine, BPEfastApplyLine

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/LASER#51]
We are using LASER line by line so using 

```python
line = lines[index]
        # romanize some languages
        romanize = True if lang in ROMANIZED_LANGUAGES else False
        
        # tokenize
        token = TokenLine(line,
                    lang=lang,
                    romanize=romanize,
                    lower_case=True)

        # bpe
        bpe = BPEfastApplyLine(token,bpe_codes)

        # encode
        encoded = EncodeLine(model,bpe)
```

where the new `EncodeLine` looks line

```python
# Encode sentences string
def EncodeLine(encoder, line):
    verbose=False
   
    print ( len(line), line )
    embedding = encoder.encode_sentences( line )

    print ( embedding.shape, embedding )
    return embedding
```

Now everything works ok: `TokenLine`, `BPEfastApplyLine`, but we are not sure about the `EncodeLine` nd.array shape:

For a given sentence like  like `donde podremos estar solos, solos, solos` we get as BPE `donde pod@@ remos estar sol@@ os , sol@@ os , sol@@ os` (size:55), then the encoded shape was `(55, 1024)` after `EncodeLine`. Is that correct?

Full logging on two sentences:
```
line donde podremos estar solos, solos, solos
55 donde pod@@ remos estar sol@@ os , sol@@ os , sol@@ os

(55, 1024) [[-1.1423406e-03 -5.5885896e-05  2.2527664e-03 ...  3.7325646e-03
  -3.6964880e-03  1.1122560e-02]
 [ 2.3968022e-03 -2.3012199e-03  2.5090985e-03 ...  1.0885910e-02
  -1.7804311e-03  7.0607006e-03]
 [-5.9819245e-04  8.6139684e-04  1.0634706e-03 ...  2.4023859e-02
  -6.1983038e-03  2.8500563e-02]
 ...
 [ 2.3968022e-03 -2.3012199e-03  2.5090985e-03 ...  1.0885910e-02
  -1.7804311e-03  7.0607006e-03]
 [ 1.9327810e-02 -5.5067514e-05  1.7086942e-03 ...  2.1211503e-02
  -4.9151536e-03  3.5833105e-02]
 [ 6.4000086e-04  1.8474855e-04  9.5328852e-04 ... -1.3147421e-04
  -1.7696818e-03 -2.5204693e-03]]
line où nous pourrons être seuls,seuls,seuls
65 où nous pourr@@ ons être se@@ ul@@ s , se@@ ul@@ s , se@@ ul@@ s

(65, 1024) [[ 2.3968022e-03 -2.3012199e-03  2.5090985e-03 ...  1.0885910e-02
  -1.7804311e-03  7.0607006e-03]
 [ 4.0953397e-03 -1.6550833e-04 -2.3423209e-04 ...  1.4184720e-03
  -6.8216762e-03 -5.1830243e-03]
 [ 6.4000080e-04  1.8474844e-04  9.5328980e-04 ... -1.3147425e-04
  -1.7696820e-03 -2.5204695e-03]
 ...
 [ 6.4000080e-04  1.8474844e-04  9.5328980e-04 ... -1.3147425e-04
  -1.7696820e-03 -2.5204695e-03]
 [ 1.9327810e-02 -5.5067514e-05  1.7086942e-03 ...  2.1211503e-02
  -4.9151536e-03  3.5833105e-02]
 [ 6.4000045e-04  1.8474869e-04  9.5328881e-04 ... -1.3147409e-04
  -1.7696813e-03 -2.5204699e-03]]
```

Second question, we still need to call `IndexCreate` before calculating the similarity between embeddings like:

```python
   d, idx = IndexCreate(path +'data_' + str(i) + '.enc.' + l ,'FlatL2', verbose=verbose, save_index=False)
```

Is this step actually needed? Assumed we have the embeddings from the `EncodeLine` we have to actually run `IndexCreate`?

**Comment by hoschwenk** [comment]
You should get back a vector 1x1024 if you embed one line.
Please use "embedding = encoder.encode_sentences( [line])"

However, you also have "line = lines[index]"
It would be much more efficient to process multiple lines at once.
This will enable batch mode of the BiLSTM

You only need a FAISS index if you have a LARGE number of embeddings to compare with !
If you have only two sentences, a simple code is enough
faiss.normalize_L2(x1)
faiss.normalize_L2(x2)
numpy.dot(x1, x2)
or any equivalent code to calculate the cosine distance or normalized L2.

**Comment by loretoparisi** [comment]
Thank you, I have actually solved this changing the `EmbedLine` like this

```python
def EncodeLine(encoder, line, buffer_size=10000):
    verbose=False
    
    fp = StringIO(line)
    embeddings = []
    for sentences in buffered_read(fp, buffer_size):
        embedding = encoder.encode_sentences( sentences )
        embeddings.append(embedding)
    if len(embeddings) == 1:
        return embeddings[0]
    return embeddings
```

The main issue here is that I must handle multiple languages for different sentences, so I need to parallelize it.

**Comment by hoschwenk** [comment]
Once you have applied tokeniztion, you can apply BPE and calculate the embeddings of many sentences in one batch. BPE and the encoder are language agnostic !

**Comment by Ravikiran2611** [comment]
#95

**Comment by Ravikiran2611** [comment]
#95
