### ISSUE TITLE
Sentence Similarity Disambiguation

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/LASER#52]
For this sentence `Que le dé, que le dé, que le dé` (that is in `ES`, Spanish) and a closer translation to `EN` English that sounds like `To give it to her, to give it to her, to give it to her`, the dot product of the embedding (see https://github.com/facebookresearch/LASER/issues/44) gives out a score of `0.44`. Typically for similar sentences I get a score `>0.5` (likely similar), `>0.7` (very likely to be similar), while everything `<0.5` seems to be unlikely similar.

Now in this specific case, it seems that at first glance `Que le dé, que le dé, que le dé` is considered like `FR`, French from most of the langId neural network I run (FastText, Google Cloud, etc.). If so, this means that in the vector space the `EN` translation would be not so closer as it would be the `ES` one.

The second consideration is that, another possibile translation in Spanish is `"to be given,to be given,to be given"`, and in this case we get a `0.79` score, that means that source and targer are actually similar.

Last, if I add to the sentence more `ES` context like `Que le dé, que le dé, que le dé, come estas`, now the similarity gets closer as well to `0.68`.

So, which would be a reasonable approach to disambiguates sentences like this, that could have very close vectors in different languages?

**Comment by hoschwenk** [comment]
Hello,
LASER does not try to identify the language of the input sentence - the encoder is totally language agnostic. One only needs to specify the language for tokenization in order to handle correctly apostrophs and punctuations like "I'll" or "je l'ai vu" (the rules slightly differ between languages).
If you don't know the input language, it's probably OK to simplify specify English (with the exception of Ja and Zh which need segmentation)

In your example, results are probably ambiguous since your sentence is very special, i.e. it is not a "normal" sentence with subject-verb-object.

BTW, don't forget to normalize the embeddings if you use the dot product.

**Comment by loretoparisi** [comment]
@hoschwenk that's a good point. I bet that in the vector space the two sentences are actually very close, I mean like `cat` and `katze`, here we have `dé` in `FR` and in `ES` that have different meanings in each language. In fact if I reinforce the input adding more text in the source language like in `Que le dé, que le dé, que le dé, come estas` I will get closer to the target sentence in `EN`.
I basically know the source and the target language, so in this case I'm using the right tokenizer for both and I know that the source was `ES` and the target was `EN`, so my guess is, given that, if I could fix the model ambiguity, reinforcing the inputs. Of course we are talking about a very specific case.

For the L2 distance we normalize the embeddings like

```python
def dot_similarity_line(features):
    
    features1 = features[:len(features)//2]
    features2 = features[len(features)//2:]
    outputs = []
    for v1,v2 in zip(features1,features2):
        n1 = np.linalg.norm(v1)
        n2 = np.linalg.norm(v2)
        outputs.append(np.dot(v1, v2) / n1 / n2)
    return [round(o,3) for o in outputs]
```

thank you.

**Comment by hoschwenk** [comment]
I'm closing this issue since there seems to be no more discussion.
