### ISSUE TITLE
Document similarity task using LASER

### ISSUE THREAD

**Issue by virendra-pathak** [facebookresearch/LASER#53]
Hello,

**Task**: Given a document (each document has ~ 8-30 sentences), find k most similar documents from the dataset.
  
**Language**: English
  
**Approach**: Each document is converted to a embedding vector using LASER. Given N query vectors, I am using FAISS library for finding k nearest neighbours. Then the experiment is repeated by using TFIDF (nltk TfidfVectorizer) for embedding documents instead of LASER.
  
**Observation**: TFIDF approach perform better than the LASER. I am using recall@k where k = 1..5 as evaluation metric. However, I was expecting LASER to perform better.
  
Am I missing something? Can someone share some insight on how this might be the case?
Any revenant reference is also welcome.
  
Thanks.

**Comment by vseledkin** [comment]
Laser model data domain is sentences. So representing documents as bag of sentence embeddings is more appropriate approach. After that apply sentence (word) movers distance to find document similarity. Please share results if this will work :)

**Comment by hoschwenk** [comment]
As pointed out by vseledkin, LASER is a sentence embedding method with the property that semantically similar sentences are close in the embedding space, even if they are written in different languages.
LASER is not meant to replace traditional information retrieval methods.
What is your query ? just dome keywords or a full sentence ?
Also, if you don't need support for many languages, LASER embeddings are probably not needed and simple TF-IDF may be enough for your task.

**Comment by virendra-pathak** [comment]
@vseledkin Thanks for the suggestion. I will experiment with wmd.
  
@hoschwenk Thanks for your comment.  
>>> What is your query ? just some keywords or a full sentence ?

I have a multilingual dataset of documents (English, German, French, Chinese etc). Though the language distribution is not uniform. My query is a document (could be 5-30 sentences).
Task is to find n most similar documents (selected documents may belong to different languages).
So far, when I consider monolingual documents (any language), I notice tfidf performance is better than laser embedding.

**Comment by hoschwenk** [comment]
LASER can be used to find semantic similar SENTENCES in many languages.
In document retrieval, you're usually interested in finding documents which cover the same topic, but may contain several unrelated sentences. Therefore, I'm not sure that a bag of sentence approach is appropriate. We currently don't have a precise idea what it means to average semantic sentence embeddings.

Hope this helps.
