### ISSUE TITLE
Python subprocess.Popen “OSError: [Errno 12] Cannot allocate memory”

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/LASER#55]
This problems happens when running multiple concurrent calls to the process of calculating embeddings in `TokenLine`

```python
def TokenLine(line, lang='en', lower_case=True, romanize=False):
    assert lower_case, 'lower case is needed by all the models'
    roman = lang if romanize else 'none'
    tok = check_output(
            REM_NON_PRINT_CHAR
            + '|' + NORM_PUNC + lang
            + '|' + DESCAPE
            + '|' + MOSES_TOKENIZER + lang
            + ('| python3.6 -m jieba -d ' if lang == 'zh' else '')
            + ('|' + MECAB + '/bin/mecab -O wakati -b 50000 ' if lang == 'ja' else '')
            + '|' + ROMAN_LC + roman,
            input=line,
            encoding='UTF-8',
            shell=True)
    return tok.strip()
```

Here is the detailed strack trace:

```
  File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
INFO:default:called LaserEmbeddingHandler...
ERROR:default:[Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/tornado_api/handlers/embeddingLaserHandler.py", line 195, in post
    embeddings = vector_embedding.embedding_line(model=model_laser,lang=lang,bpe_codes=QUALITY_MODEL_PATH + "/93langs.fcodes",input_text=text)
  File "/tornado_api/deeplearning/vector_embedding.py", line 50, in embedding_line
    embeddings.append(t.result()[0].tolist() )
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tornado_api/deeplearning/similarity_search.py", line 99, in pipeline
    lower_case=lower_case)
  File "/tornado_api/deeplearning/lib/text_processing.py", line 62, in TokenLine
    shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
INFO:default:called LaserEmbeddingHandler...
ERROR:default:[Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/tornado_api/handlers/embeddingLaserHandler.py", line 195, in post
    embeddings = vector_embedding.embedding_line(model=model_laser,lang=lang,bpe_codes=QUALITY_MODEL_PATH + "/93langs.fcodes",input_text=text)
  File "/tornado_api/deeplearning/vector_embedding.py", line 50, in embedding_line
    embeddings.append(t.result()[0].tolist() )
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tornado_api/deeplearning/similarity_search.py", line 99, in pipeline
    lower_case=lower_case)
  File "/tornado_api/deeplearning/lib/text_processing.py", line 62, in TokenLine
    shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

**Comment by hoschwenk** [comment]
Why do you have multiple CONCURRENT calls to TokenLine ?
It would be much more efficient to collect several lines of text and to tokenize, apply BP and calculate th emebddings in one call (using the file version)>
This will be MUCH faster since the BiLSTM will run in batch mode !
If you're running multiple instances of the tool, you'll charge the models many times into memory which may lead to the out of memory error.
I guess that in your application, some type of "server mode" would be more appropriate.

**Comment by loretoparisi** [comment]
@hoschwenk thanks, so basically we do this call for a whole document at time i.e. each document has multiple lines. The biLSTM is initialized once in the server and passed back to the tokenizer / bpe pipeline, so it is loaded once in memory, but as you mentioned what happens is that the `subprocess` call cannot allocate memory due to subsequent / concurrent calls.
Thank you I will find another possibile approach.

**Comment by loretoparisi** [comment]
@hoschwenk last question is about using Moses Tokenizer directly in Python, instead of using the command line tool that requires a subprocess command, like the NLTK implementation here https://www.nltk.org/_modules/nltk/tokenize/moses.html.
Do you think could it work ok? I assume it can do all the things like removing non printing chars, punctation, special chars de-escaping, etc.
Thanks

**Comment by hoschwenk** [comment]
@loretoparisi if this Python tool produces exactly the same results than the Moses tools, than you can obviously use it. Having everything in Python would be indeed more convenient, in particular when handling individual lines... 
What is the license of NLTK ?

**Comment by loretoparisi** [comment]
@hoschwenk that's a good question. In fact Pytorch torch project had to remove it after integrating. Then some torch developer turned it into a separated project with MIT licensing, so now it is integrated back into Pytorch! Here it is: https://github.com/alvations/sacremoses

And That's the issue about licensing:
https://github.com/pytorch/text/issues/306

My aim is to integrate this and replace it on the `TokenLine` and `Token` both.  I have also asked SacredMoses guys to be sure it covers all the `perl` scripts:

https://github.com/alvations/sacremoses/issues/44

**Comment by loretoparisi** [comment]
@hoschwenk It seems we can do everything programmatically like this

```python
def TokenLine(line, lang='en', lower_case=True, romanize=False):
    
    # normalize-punctuation.perl -l
    mpn = MosesPunctNormalizer(lang = lang)

    # tokenizer.perl -q -no-escape -threads 20 -l
    mtok = MosesTokenizer(lang = lang)

    # punct normalizer
    line = mpn.normalize(line)

    # tokenizer, escape XML, join tokens, no hyphen dash split
    tok = mtok.tokenize(line, escape=True, return_str=True, aggressive_dash_splits=False)

    if lang == 'zh':
        # jieba -d
        seg_list = jieba.cut(tok, cut_all=False)
        tok = " ".join(seg_list)
    elif lang == 'ja':
        # mecab -O wakati -b 50000
        mecab = MeCab.Tagger("-Owakati b5000")
        tok = mecab.parse(tok)

    if romanize:
        # romanize_lc.py -l
        line = translit(line, lang, reversed=True)
    # lowercase
    if lower_case:
        line = line.lower()

    return tok.strip()
```
This will require `sacremoses`, `meCab` and `jieba` to be installed. I have still to have command line parameters match to SacreMoses aPI parameters confirmed, but I think we are almost there!

**Comment by loretoparisi** [comment]
It's [now](https://github.com/glample/fastBPE/issues/12) possibile to use fastBPE directly from Python, I have suggest to add a Python wrapper and thanks to glampe now it has one!

```python
import fastBPE

bpe = fastBPE.fastBPE(codes_path, vocab_path)
bpe.apply(["Roasted barramundi fish", "Centrally managed over a client-server architecture"])

>> ['Ro@@ asted barr@@ am@@ un@@ di fish', 'Centr@@ ally managed over a cli@@ ent-@@ server architecture']
```

so the `BPEfastApply` becomes like

```python
def BPEfastApplyLine(line, bpe_codes):
    bpe_vocab = bpe_codes.replace('fcodes', 'fvocab')
    if not os.path.isfile(bpe_vocab):
        print(' - fast BPE: focab file not found {}'.format(bpe_vocab))
        bpe_vocab = ''

    bpe = fastBPE(bpe_codes, bpe_vocab)
    # fastBPE/fast applybpe ofn ifn bpe_codes bpe_vocab
    lines = re.split(r'[\n]',text)
    codes = bpe.apply(lines)
    return codes
```

of course the best approach is initialize `fastBPE` outside once.

**Comment by hoschwenk** [comment]
I know, he is a colleague in the same lab and I told him that we would need this ;-)
I'll update the code soon ..

**Comment by loretoparisi** [comment]
@hoschwenk hehehe amazing, in the meanwhile I did the update by our side and it seems to work properly. I have only some doubt about SacreMoses parameters here

```python
# normalize-punctuation.perl -l
    mpn = MosesPunctNormalizer(lang = lang)

    # tokenizer.perl -q -no-escape -threads 20 -l
    mtok = MosesTokenizer(lang = lang)

    # punct normalizer
    line = mpn.normalize(line)

    # tokenizer, escape XML, join tokens, no hyphen dash split
    tok = mtok.tokenize(line, escape=True, return_str=True, aggressive_dash_splits=False)
```

not sure if the hyphen split should be aggressive with `aggressive_dash_splits=False`, while the `escape=True` should be ok (according to the code it is the XML escaping).
I say that because if I look at the L2 norm, the values are almost correct (the distance is reasonable), but not the same (like for a distant pair I have got 0.44 before, now I get a 0.47), so some pre-processing it is not yours exactly, maybe due to those Moses parameters.

**Comment by simonefrancia** [comment]
Hi @hoschwenk, thanks for your support.
We are doing some tests and we realized that using this configuration of parameters,

```tok = mtok.tokenize(line, escape=False, return_str=True, aggressive_dash_splits=False)```

we obtain the same scores that we got with the previous version of Moses Tokenizer (from script command) ;
so putting ```escape=False``` gives the expected results. 
Do you think this modification is correct or it's better to maintain ```escape=True```?

Thanks

**Comment by hoschwenk** [comment]
Hi @simonefrancia ,
you should use  escape=False since this corresponds to "-no-escape" as used with the Moses tool.
It's good to know that you achieve the same results.

**Comment by simonefrancia** [comment]
I think also this choice is the best in our case. An example with the sentence:
```hoy quiero que te quede' a dormir```

Case  1: escape=True
Token:
```hoy quiero que te quede &apos; a dormir```
Bpe:
```hoy quiero que te qu@@ ede &@@ apo@@ s@@ ; a dormir```

Case 2: escape=False
Token:
```hoy quiero que te quede ' a dormir```
BPE:
```hoy quiero que te qu@@ ede ' a dormir```

So, in my opinion the second one is the most likely, because Tokenization is good.

**Comment by loretoparisi** [comment]
@hoschwenk thank you for your help it was very helpful!

**Comment by loretoparisi** [comment]
@hoschwenk if it can help `SacreMoses` author documented how to use it programmatically. At the end we did in the right way, and now LASER works programmatically in the whole pipeline!
