### ISSUE TITLE
fastBPE install

### ISSUE THREAD

**Issue by Stolaine** [facebookresearch/LASER#62]
In the shell script intsall_external_tools.sh under install fastBPE section the command 
`g++ -std=c++11 -pthread -O3 fast.cc -o fast`
has fast.cc in it. but there is no file named fast.cc in repository of fastBPE. it contains `main.cc`.

it is showing error while trying to execute `bash ./install_external_tools.sh`
```
g++: error: fast.cc: No such file or directory
g++: fatal error: no input files
compilation terminated.
```

**Comment by hoschwenk** [comment]
Hello,
I had updated the code to support the new version of fastBPE, but one file was not updated (./install_external_tools.sh)
Please pull again and compilation should work now.

**Comment by gvskalyan** [comment]
https://pypi.org/project/fastBPE/ - with this please remove installfastbpe() in build_external_tools.sh once README gets updated in fastBPE repo

**Comment by tvinith** [comment]
gcc: error: fastBPE/fastBPE.cpp: No such file or directory

**Comment by tvinith** [comment]
pip install cython before installing helped me ..
