### ISSUE TITLE
Sentiment Classification Task with RNN from LASER embedding

### ISSUE THREAD

**Issue by simonefrancia** [facebookresearch/LASER#66]
Hi,
we are trying to build a cross-lingual sentiment classifier starting from LASER embedding. 
The first step we did was to build a simple classifier that has as input the embedding with size 1024 of a sentence and ,adding some hidden layers, makes a prediction between 5 classes.
We take as example the MLDOC task you provide and we saw good results in that, but also something to improve.

Some example of errors:

```
"my mother is not angry" -> "negative"

"I am not the worst" -> "negative"
```

I think that, especially for the sentiment, it's important to maintain a context that is updated everytime that a word is analyzed inside the sentence, because potentially every word could overturn the sentiment of the entire sentence. 

So I think we have to move to RNNs. In this sense, I would like to create an embedding LASER for every word and use an RNN to create an hidden state that can change based on words the network sees. 
Do you think this approach could work with LASER embedding at word level? 
Thanks

**Comment by hoschwenk** [comment]
Hello,
LASER already uses RNN, more specifically bidirectional LSTMs.
Also, LASER embeddings are for a whole sentence not a word. Please verify that you correctly embed whole sentences at once.
With respect to your example, LASER, and basically all other similar approaches are statistical. One can often find some examples for which the results are wrong. It is recommended to calculate the average error on a sufficient large test corpus. As an extreme example, if the above example were the only one out of 1000, than you're approach would be working very well.
However, if you observe hundreds of wrong examples like this, than we must find ways to improve it...

Hope this helps.

**Comment by simonefrancia** [comment]
Ok thanks for your support.
I will make some test as you suggested about this.
My idea was this: beside LASER embedding was trained with bidirectional LSTMs, its aim was to incorporate semantic value for all words between all languages; so I thought that a fine-tuning with another RNN (for the reason I mentioned before ) specified on sentiment could help in this way.
