### ISSUE TITLE
There is no Latavian language.

### ISSUE THREAD

**Issue by MikusR** [facebookresearch/LASER#7]
README.md Has Latavian as supported language, but it should say Latvian. Your blogpost https://code.fb.com/ai-research/laser-multilingual-sentence-embeddings/ also has an animation with the same typo.

**Comment by stefan-it** [comment]
I corrected the spelling mistake in #10 :)

**Comment by hoschwenk** [comment]
Hello,
Thanks for spotting this spelling error.
I've corrected it.
