### ISSUE TITLE
sentence embedding for japanese: one vector instead of actual number of sentences

### ISSUE THREAD

**Issue by asiliskins** [facebookresearch/LASER#71]
I get one vector after sentence embedding for japanese, for other languages everything works well.

**input:**
echo jap_text.txt | python laser/source/embed.py --encoder laser/models/bilstm.93langs.2018-12-26.pt --token-lang jpn --bpe-codes laser/models/93langs.fcodes --output jptest.vec --verbose

**output:**
 - Encoder: loading laser/models/bilstm.93langs.2018-12-26.pt
 - Tokenizer:  in language ja  
WARNING: No known abbreviations for language 'ja', attempting fall-back to English version...
ja
 - fast BPE: processing tok
 - Encoder: bpe to jptest.vec
 - Encoder: 1 sentences in 0s

but the actual number of lines (sentences) in jap_text.txt is 32 

after Token() (there is no problem with MeCab) and BPEfastApply() number of lines doesn't change, so I think there is a problem in SentenceEncoder()

**Comment by asiliskins** [comment]
the encoding of text is UTF-8

**Comment by prabhakar267** [comment]
@asiliskins Did you manager to find the issue?
