### ISSUE TITLE
Language code to get embeddings

### ISSUE THREAD

**Issue by ramji-c** [facebookresearch/LASER#74]
In order to use embed.sh, a 2 character language code is needed. Is there a list of these language codes that are allowed? is a general guideline followed or something custom? For example, to get embeddings in Spanish, should I use "es" or "sp"?

**Comment by hoschwenk** [comment]
Please use the standard ISO 2-letter language codes (or 3 letter when there's no 2 letter code).
"es" is correct for Spanish.
You'll also find the list of codes in the arXiv paper
