### ISSUE TITLE
Wget with 429 Errors

### ISSUE THREAD

**Issue by alvations** [facebookresearch/LASER#79]
While trying to download the corpora, we are receiving 429 errors:

```
wget https://dl.fbaipublicfiles.com/laser/WikiMatrix/v1/WikiPedia.wuu-zh.tsv
--2019-07-15 20:47:56--  https://dl.fbaipublicfiles.com/laser/WikiMatrix/v1/WikiPedia.wuu-zh.tsv
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 104.20.22.166, 104.20.6.166, 2606:4700:10::6814:6a6, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|104.20.22.166|:443... connected.
HTTP request sent, awaiting response... 429 Too Many Requests
2019-07-15 20:47:56 ERROR 429: Too Many Requests.
```

**Comment by neubig** [comment]
Change `WikiPedia` to `WikiMatrix`, and add `.gz` to the end and it should work.

**Comment by mayhewsw** [comment]
https://github.com/facebookresearch/LASER/pull/81

**Comment by alvations** [comment]
Thanks @neubig!! It works =)

**Comment by alvations** [comment]
Actually, it kinda worked for a while, then the 429 appears again =(

```
WikiMatrix.mk-pt.tsv  72%[=============>      ]  33.27M   141KB/s    in 21m 26s 

2019-07-16 09:11:34 (26.5 KB/s) - Read error at byte 34889086/48284706 (Success). Retrying.

--2019-07-16 09:11:35--  (try: 2)  https://dl.fbaipublicfiles.com/laser/WikiMatrix/v1/WikiMatrix.mk-pt.tsv.gz
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|104.20.6.166|:443... connected.
HTTP request sent, awaiting response... 429 Too Many Requests
2019-07-16 09:11:35 ERROR 429: Too Many Requests.
```

**Comment by hoschwenk** [comment]
Does this happen only for that file or for all ?
Have you tried to rerun wget  ?

**Comment by prajdabre** [comment]
Hello,
I too have the same problem.
My first 200 files downloaded properly but the rest gave HTTP status 429  "Too many requests" error.

**Comment by hoschwenk** [comment]
Hmm, it could b ethat there's a limit on the number of files that each user/IP can download sequentially from AWS. We will create one big tar-file with all the data. I was assuming that most people would only download some languages since all the data is big (70 GB !)

**Comment by hoschwenk** [comment]
Hi,
I added one tar file with all the 1620 alignments.
This should simplify the download, but it is 65GB !

**Comment by alvations** [comment]
@hoschwenk  Thanks! What's the full file path for that 65GB file?`https://dl.fbaipublicfiles.com/laser/WikiMatrix/v1/`

**Comment by hoschwenk** [comment]
Yes, the full file name is given in the WikiMatrix README
