### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp498vksrc/bpe'

### ISSUE THREAD

**Issue by zilinly** [facebookresearch/LASER#87]
when I install all of these tools offline, FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp498vksrc/bpe' appears........

**Comment by hoschwenk** [comment]
I similar issues was reported before and it was caused to wrong/missing installation of the 3rd party software.
In practice, this error means that the BPE processed files were not created, potentially because tokenisation already failed. Both rely on 3rd party software.

**Comment by zilinly** [comment]
> I similar issues was reported before and it was caused to wrong/missing installation of the 3rd party software.
> In practice, this error means that the BPE processed files were not created, potentially because tokenisation already failed. Both rely on 3rd party software.

tok file is generated，
maybe the environment of low gcc。。

**Comment by hoschwenk** [comment]
an the tok file is not empty ?
(could happen wit ha broken zh ot ja tokenizer)

**Comment by gkaradzhov** [comment]
For me, the problem was with using gcc to install fastBPE. I installed Cython `pip3 install Cython` and reran the full installation process.

**Comment by zilinly** [comment]
> For me, the problem was with using gcc to install fastBPE. I installed Cython `pip3 install Cython` and reran the full installation process.

Cython is ready, all of the problem is focused gcc....

**Comment by hoschwenk** [comment]
Yes, Cyton is needed for fastbpe (it is mentioned in the installation instructions ;-)
It seems that your problem is resolved and I'll close the issue.

**Comment by zilinly** [comment]
> Yes, Cyton is needed for fastbpe (it is mentioned in the installation instructions ;-)
> It seems that your problem is resolved and I'll close the issue.

yes

**Comment by vigneshmj1997** [comment]
i do have Cython installed along with all other nessary packages and  yet i am getting the same error
