### ISSUE TITLE
sentence embeddings

### ISSUE THREAD

**Issue by divyag11** [facebookresearch/LASER#90]
LASER does not consider language while giving sentence representation.But what does it consider to give embeddings for the input sentence such that the similar sentences in different language end up together in same neighbourhood.
Kindly explain.

**Comment by hoschwenk** [comment]
Please have a look at the paper "Margin-based Parallel Corpus Mining with Multilingual Sentence Embeddings" on ArXiv (referenced in the master README)
It explains all the theory in detail how LASER was trained.
